// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsAr = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "اختر لغتك",
  "myResumes": "سيري الذاتية",
  "newResume": "سيرة جديدة",
  "noResumes": "لا توجد سير ذاتية بعد",
  "noResumesHint": "ابدأ بإنشاء أول سيرة ذاتية احترافية",
  "untitled": "سيرة بدون عنوان",
  "personal": "البيانات الشخصية",
  "summary": "نبذة مختصرة",
  "experience": "الخبرات",
  "education": "التعليم",
  "skills": "المهارات",
  "languages": "اللغات",
  "projects": "المشاريع",
  "design": "التصميم",
  "ai": "الذكاء الاصطناعي",
  "preview": "معاينة وتصدير",
  "settings": "الإعدادات",
  "uiLanguage": "لغة التطبيق",
  "premium": "النسخة المميزة",
  "cancel": "إلغاء",
  "delete": "حذف",
  "duplicate": "نسخ",
  "confirmDelete": "هل تريد حذف هذه السيرة؟",
  "add": "إضافة",
  "fullName": "الاسم الكامل",
  "jobTitle": "المسمى الوظيفي",
  "email": "البريد الإلكتروني",
  "phone": "رقم الجوال",
  "city": "المدينة والدولة",
  "website": "الموقع أو LinkedIn",
  "company": "الجهة",
  "position": "المسمى",
  "location": "المكان",
  "startDate": "البداية",
  "endDate": "النهاية",
  "present": "حتى الآن",
  "description": "الوصف (سطر لكل نقطة)",
  "school": "المؤسسة التعليمية",
  "degree": "الدرجة / التخصص",
  "level": "المستوى",
  "skillHint": "أضف مهارة",
  "projectName": "اسم المشروع",
  "projectLink": "الرابط",
  "langName": "اللغة",
  "suggestions": "اقتراحات",
  "actionVerbs": "أفعال قوية للبدء بها",
  "completeness": "اكتمال السيرة",
  "missing": "ينقصك",
  "resumeLanguage": "لغة السيرة",
  "accent": "اللون الرئيسي",
  "template": "القالب",
  "photo": "الصورة الشخصية",
  "choosePhoto": "اختيار صورة",
  "removePhoto": "إزالة الصورة",
  "premiumTitle": "قالب مميز",
  "premiumBody": "هذا القالب ضمن النسخة المميزة.",
  "activateDemo": "تفعيل (تجريبي)",
  "premiumActive": "النسخة المميزة مفعّلة",
  "lv0": "مبتدئ",
  "lv1": "متوسط",
  "lv2": "متقدم",
  "lv3": "طلاقة",
  "lv4": "لغة أم",
  "tpl_classic": "كلاسيكي",
  "tpl_modern": "عصري",
  "tpl_minimal": "بسيط",
  "tpl_banner": "لافتة",
  "tpl_compact": "مدمج",
  "tpl_executive": "تنفيذي",
  "resumeName": "اسم الملف",
  "about": "حول التطبيق",
  "free": "مجاني",
  "aiTools": "أدوات الذكاء الاصطناعي",
  "aiGenerate": "اكتب بالذكاء الاصطناعي",
  "aiImprove": "حسّن بالذكاء الاصطناعي",
  "aiBullets": "اقتراح نقاط للخبرة",
  "aiSkills": "اقتراح مهارات بالذكاء الاصطناعي",
  "aiWorking": "جارٍ العمل…",
  "aiError": "تعذّر تنفيذ الطلب. حاول مرة أخرى.",
  "apply": "تطبيق",
  "copy": "نسخ",
  "copied": "تم النسخ",
  "aiOfflineNote": "الوضع الأساسي. اربط خادم ذكاء اصطناعي من الإعدادات لتفعيل الميزات الكاملة.",
  "aiQuotaReached": "انتهى الحد اليومي المجاني للذكاء الاصطناعي",
  "aiFreeLeft": "مرات الذكاء الاصطناعي المجانية المتبقية اليوم",
  "aiReview": "مراجعة سيرتي",
  "aiReviewHint": "احصل على تقييم ونصائح للتحسين",
  "aiJobMatch": "مطابقة مع وظيفة",
  "aiJobHint": "الصق وصف الوظيفة لمعرفة الكلمات المفتاحية الناقصة",
  "aiJobField": "وصف الوظيفة",
  "aiAnalyze": "تحليل",
  "aiCoverLetter": "خطاب التقديم",
  "aiCoverHint": "اكتب خطاب تقديم مخصصاً للوظيفة",
  "aiTranslate": "ترجمة السيرة",
  "aiTranslateHint": "أنشئ نسخة مترجمة بلغة أخرى",
  "targetLanguage": "اللغة المطلوبة",
  "aiTranslated": "تم إنشاء النسخة المترجمة",
  "aiTranslateNeedsServer": "الترجمة تحتاج خادم ذكاء اصطناعي. اضبطه من الإعدادات.",
  "matchScore": "نسبة التطابق",
  "matched": "كلمات متطابقة",
  "missingKw": "كلمات ناقصة",
  "aiServer": "عنوان خادم الذكاء الاصطناعي",
  "aiServerHint": "اتركه فارغاً لاستخدام الافتراضي",
  "tips": "نصائح",
  "rvScore": "تقييم السيرة",
  "rvSummaryShort": "النبذة قصيرة. اجعلها من جملتين إلى أربع جمل.",
  "rvNoNumbers": "أضف أرقاماً لإنجازاتك (نسب، مبالغ، أعداد).",
  "rvFewSkills": "اذكر ست مهارات ذات صلة على الأقل.",
  "rvNoBullets": "اشرح خبراتك بنقطة لكل إنجاز.",
  "rvGood": "سيرتك تبدو قوية.",
  "clTemplate": "السادة المحترمون في قسم التوظيف،\n\nأتقدم لشغل وظيفة {job}. من أبرز ما أتميّز به: {skills}، وأتطلع إلى فرصة لمناقشة كيف يمكنني الإسهام في فريقكم.\n\nمع خالص التقدير،\n{name}",
  "bulletHint": "اكتب ما فعلته والنتيجة",
  "editPhoto": "تعديل الصورة",
  "cropHint": "اسحب وقرّب بإصبعين للقص",
  "rotate": "تدوير",
  "filters": "الفلاتر",
  "brightness": "السطوع",
  "contrast": "التباين",
  "saturation": "التشبّع",
  "reset": "إعادة ضبط",
  "f_original": "الأصلية",
  "f_bw": "أبيض وأسود",
  "f_sepia": "سيبيا",
  "f_warm": "دافئ",
  "f_cool": "بارد",
  "f_vivid": "زاهٍ",
  "f_fade": "باهت",
  "pickDate": "اختر التاريخ",
  "clear": "مسح",
  "share": "مشاركة",
  "saveFile": "حفظ",
  "saved": "تم الحفظ",
  "saveFailed": "تعذّر حفظ الملف",
  "sumYears": "{job} بخبرة تزيد عن {years} سنوات، أحرص على تحقيق نتائج ملموسة والعمل بروح الفريق.",
  "sumPlain": "{job} طموح وسريع التعلّم، أسعى لتقديم قيمة حقيقية والنمو المهني المستمر.",
  "sumSkills": "أتميّز في: {skills}.",
  "fallbackJob": "محترف",
  "verbs": "قدت|طورت|أطلقت|حسّنت|خفّضت|أدرت|صممت|حققت|نفّذت|رفعت",
  "softSkills": "التواصل الفعّال|العمل الجماعي|حل المشكلات|إدارة الوقت|القيادة|المرونة|التفكير النقدي|الإبداع|الدقة والانتباه للتفاصيل|التفاوض|خدمة العملاء|إدارة المشاريع|التفكير التحليلي|مهارات العرض والإلقاء",
};
