// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsDe = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Sprache auswählen",
  "myResumes": "Meine Lebensläufe",
  "newResume": "Neuer Lebenslauf",
  "noResumes": "Noch keine Lebensläufe",
  "noResumesHint": "Erstelle deinen ersten professionellen Lebenslauf",
  "untitled": "Unbenannter Lebenslauf",
  "personal": "Persönliche Daten",
  "summary": "Profil",
  "experience": "Berufserfahrung",
  "education": "Ausbildung",
  "skills": "Kenntnisse",
  "languages": "Sprachen",
  "projects": "Projekte",
  "design": "Design",
  "ai": "KI",
  "preview": "Vorschau & Export",
  "settings": "Einstellungen",
  "uiLanguage": "App-Sprache",
  "premium": "Premium",
  "cancel": "Abbrechen",
  "delete": "Löschen",
  "duplicate": "Duplizieren",
  "confirmDelete": "Diesen Lebenslauf löschen?",
  "add": "Hinzufügen",
  "fullName": "Vollständiger Name",
  "jobTitle": "Berufsbezeichnung",
  "email": "E-Mail",
  "phone": "Telefon",
  "city": "Stadt, Land",
  "website": "Website oder LinkedIn",
  "company": "Unternehmen",
  "position": "Position",
  "location": "Ort",
  "startDate": "Beginn",
  "endDate": "Ende",
  "present": "Heute",
  "description": "Beschreibung (ein Aufzählungspunkt pro Zeile)",
  "school": "Bildungseinrichtung",
  "degree": "Abschluss / Fachrichtung",
  "level": "Niveau",
  "skillHint": "Kenntnis hinzufügen",
  "projectName": "Projektname",
  "projectLink": "Link",
  "langName": "Sprache",
  "suggestions": "Vorschläge",
  "actionVerbs": "Starke Verben für den Einstieg",
  "completeness": "Vollständigkeit des Lebenslaufs",
  "missing": "Fehlt",
  "resumeLanguage": "Sprache des Lebenslaufs",
  "accent": "Akzentfarbe",
  "template": "Vorlage",
  "photo": "Foto",
  "choosePhoto": "Foto auswählen",
  "removePhoto": "Foto entfernen",
  "premiumTitle": "Premium-Vorlage",
  "premiumBody": "Diese Vorlage gehört zu Premium.",
  "activateDemo": "Aktivieren (Demo)",
  "premiumActive": "Premium ist aktiv",
  "lv0": "Grundkenntnisse",
  "lv1": "Mittelstufe",
  "lv2": "Fortgeschritten",
  "lv3": "Fließend",
  "lv4": "Muttersprache",
  "tpl_classic": "Klassisch",
  "tpl_modern": "Modern",
  "tpl_minimal": "Minimalistisch",
  "tpl_banner": "Banner",
  "tpl_compact": "Kompakt",
  "tpl_executive": "Executive",
  "resumeName": "Dateiname",
  "about": "Über die App",
  "free": "Kostenlos",
  "aiTools": "KI-Werkzeuge",
  "aiGenerate": "Mit KI schreiben",
  "aiImprove": "Mit KI verbessern",
  "aiBullets": "Stichpunkte vorschlagen",
  "aiSkills": "Kenntnisse per KI vorschlagen",
  "aiWorking": "Wird bearbeitet…",
  "aiError": "KI-Anfrage fehlgeschlagen. Bitte erneut versuchen.",
  "apply": "Übernehmen",
  "copy": "Kopieren",
  "copied": "Kopiert",
  "aiOfflineNote": "Basismodus. Verbinde in den Einstellungen einen KI-Server für alle Funktionen.",
  "aiQuotaReached": "Tägliches kostenloses KI-Limit erreicht",
  "aiFreeLeft": "Verbleibende kostenlose KI-Nutzungen heute",
  "aiReview": "Lebenslauf prüfen",
  "aiReviewHint": "Bewertung und Verbesserungstipps erhalten",
  "aiJobMatch": "Mit Stelle abgleichen",
  "aiJobHint": "Stellenanzeige einfügen, um fehlende Schlüsselwörter zu sehen",
  "aiJobField": "Stellenbeschreibung",
  "aiAnalyze": "Analysieren",
  "aiCoverLetter": "Anschreiben",
  "aiCoverHint": "Ein passendes Anschreiben verfassen",
  "aiTranslate": "Lebenslauf übersetzen",
  "aiTranslateHint": "Eine übersetzte Kopie in einer anderen Sprache erstellen",
  "targetLanguage": "Zielsprache",
  "aiTranslated": "Übersetzte Kopie erstellt",
  "aiTranslateNeedsServer": "Die Übersetzung benötigt einen KI-Server. Richte ihn in den Einstellungen ein.",
  "matchScore": "Übereinstimmung",
  "matched": "Gefundene Schlüsselwörter",
  "missingKw": "Fehlende Schlüsselwörter",
  "aiServer": "Adresse des KI-Servers",
  "aiServerHint": "Leer lassen, um den Standard zu verwenden",
  "tips": "Tipps",
  "rvScore": "Bewertung des Lebenslaufs",
  "rvSummaryShort": "Dein Profil ist kurz. Ziel sind 2 bis 4 Sätze.",
  "rvNoNumbers": "Ergänze Zahlen zu deinen Erfolgen (Prozent, Beträge, Mengen).",
  "rvFewSkills": "Nenne mindestens 6 relevante Kenntnisse.",
  "rvNoBullets": "Beschreibe deine Erfahrung mit einem Stichpunkt pro Erfolg.",
  "rvGood": "Dein Lebenslauf wirkt überzeugend.",
  "clTemplate": "Sehr geehrte Damen und Herren,\n\nhiermit bewerbe ich mich um die Stelle als {job}. Zu meinen Stärken zählen {skills}, und ich freue mich auf ein Gespräch darüber, wie ich Ihr Team unterstützen kann.\n\nMit freundlichen Grüßen\n{name}",
  "bulletHint": "ergänze, was du getan hast und das Ergebnis",
  "editPhoto": "Foto bearbeiten",
  "cropHint": "Zum Zuschneiden ziehen und zoomen",
  "rotate": "Drehen",
  "filters": "Filter",
  "brightness": "Helligkeit",
  "contrast": "Kontrast",
  "saturation": "Sättigung",
  "reset": "Zurücksetzen",
  "f_original": "Original",
  "f_bw": "S/W",
  "f_sepia": "Sepia",
  "f_warm": "Warm",
  "f_cool": "Kalt",
  "f_vivid": "Lebhaft",
  "f_fade": "Verblasst",
  "pickDate": "Datum wählen",
  "clear": "Löschen",
  "share": "Teilen",
  "saveFile": "Speichern",
  "saved": "Gespeichert",
  "saveFailed": "Datei konnte nicht gespeichert werden",
  "sumYears": "Ergebnisorientierte/r {job} mit über {years} Jahren Erfahrung, mit Fokus auf messbare Wirkung und Teamarbeit.",
  "sumPlain": "Motivierte/r {job} mit schneller Auffassungsgabe, bereit, echten Mehrwert zu schaffen und sich weiterzuentwickeln.",
  "sumSkills": "Stärken: {skills}.",
  "fallbackJob": "Fachkraft",
  "verbs": "Geleitet|Entwickelt|Eingeführt|Verbessert|Reduziert|Verwaltet|Gestaltet|Erreicht|Geliefert|Gesteigert",
  "softSkills": "Kommunikation|Teamarbeit|Problemlösung|Zeitmanagement|Führung|Anpassungsfähigkeit|Kritisches Denken|Kreativität|Sorgfalt|Verhandlungsgeschick|Kundenservice|Projektmanagement|Analytisches Denken|Präsentationsfähigkeit",
};
