// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsEn = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Choose your language",
  "myResumes": "My resumes",
  "newResume": "New resume",
  "noResumes": "No resumes yet",
  "noResumesHint": "Create your first professional resume",
  "untitled": "Untitled resume",
  "personal": "Personal details",
  "summary": "Summary",
  "experience": "Experience",
  "education": "Education",
  "skills": "Skills",
  "languages": "Languages",
  "projects": "Projects",
  "design": "Design",
  "ai": "AI",
  "preview": "Preview & export",
  "settings": "Settings",
  "uiLanguage": "App language",
  "premium": "Premium",
  "cancel": "Cancel",
  "delete": "Delete",
  "duplicate": "Duplicate",
  "confirmDelete": "Delete this resume?",
  "add": "Add",
  "fullName": "Full name",
  "jobTitle": "Job title",
  "email": "Email",
  "phone": "Phone",
  "city": "City, Country",
  "website": "Website or LinkedIn",
  "company": "Company",
  "position": "Position",
  "location": "Location",
  "startDate": "Start",
  "endDate": "End",
  "present": "Present",
  "description": "Description (one bullet per line)",
  "school": "School",
  "degree": "Degree / Field",
  "level": "Level",
  "skillHint": "Add a skill",
  "projectName": "Project name",
  "projectLink": "Link",
  "langName": "Language",
  "suggestions": "Suggestions",
  "actionVerbs": "Strong verbs to start with",
  "completeness": "Resume completeness",
  "missing": "Missing",
  "resumeLanguage": "Resume language",
  "accent": "Accent color",
  "template": "Template",
  "photo": "Photo",
  "choosePhoto": "Choose photo",
  "removePhoto": "Remove photo",
  "premiumTitle": "Premium template",
  "premiumBody": "This template is part of Premium.",
  "activateDemo": "Activate (demo)",
  "premiumActive": "Premium is active",
  "lv0": "Basic",
  "lv1": "Intermediate",
  "lv2": "Advanced",
  "lv3": "Fluent",
  "lv4": "Native",
  "tpl_classic": "Classic",
  "tpl_modern": "Modern",
  "tpl_minimal": "Minimal",
  "tpl_banner": "Banner",
  "tpl_compact": "Compact",
  "tpl_executive": "Executive",
  "resumeName": "File name",
  "about": "About",
  "free": "Free",
  "aiTools": "AI tools",
  "aiGenerate": "Write with AI",
  "aiImprove": "Improve with AI",
  "aiBullets": "Suggest bullet points",
  "aiSkills": "Suggest skills with AI",
  "aiWorking": "Working…",
  "aiError": "AI request failed. Try again.",
  "apply": "Apply",
  "copy": "Copy",
  "copied": "Copied",
  "aiOfflineNote": "Basic mode. Connect an AI server in Settings for full AI.",
  "aiQuotaReached": "Daily free AI limit reached",
  "aiFreeLeft": "Free AI uses left today",
  "aiReview": "Review my resume",
  "aiReviewHint": "Get a score and tips to improve",
  "aiJobMatch": "Match with a job",
  "aiJobHint": "Paste a job description to see keyword gaps",
  "aiJobField": "Job description",
  "aiAnalyze": "Analyze",
  "aiCoverLetter": "Cover letter",
  "aiCoverHint": "Write a tailored cover letter",
  "aiTranslate": "Translate resume",
  "aiTranslateHint": "Create a translated copy in another language",
  "targetLanguage": "Target language",
  "aiTranslated": "Translated copy created",
  "aiTranslateNeedsServer": "Translation needs an AI server. Set it up in Settings.",
  "matchScore": "Match",
  "matched": "Matched keywords",
  "missingKw": "Missing keywords",
  "aiServer": "AI server address",
  "aiServerHint": "Leave empty to use the default",
  "tips": "Tips",
  "rvScore": "Resume score",
  "rvSummaryShort": "Your summary is short. Aim for 2 to 4 sentences.",
  "rvNoNumbers": "Add numbers to your achievements (percentages, amounts, counts).",
  "rvFewSkills": "List at least 6 relevant skills.",
  "rvNoBullets": "Describe your experience with one bullet per achievement.",
  "rvGood": "Your resume looks strong.",
  "clTemplate": "Dear Hiring Manager,\n\nI am writing to apply for the {job} position. My strengths include {skills}, and I would welcome the chance to discuss how I can contribute to your team.\n\nSincerely,\n{name}",
  "bulletHint": "add what you did and the result",
  "editPhoto": "Edit photo",
  "cropHint": "Drag and pinch to crop",
  "rotate": "Rotate",
  "filters": "Filters",
  "brightness": "Brightness",
  "contrast": "Contrast",
  "saturation": "Saturation",
  "reset": "Reset",
  "f_original": "Original",
  "f_bw": "B&W",
  "f_sepia": "Sepia",
  "f_warm": "Warm",
  "f_cool": "Cool",
  "f_vivid": "Vivid",
  "f_fade": "Fade",
  "pickDate": "Select date",
  "clear": "Clear",
  "share": "Share",
  "saveFile": "Save",
  "saved": "Saved",
  "saveFailed": "Could not save the file",
  "sumYears": "Results-driven {job} with {years}+ years of experience, focused on delivering measurable impact and collaborating across teams.",
  "sumPlain": "Motivated {job} and fast learner, eager to deliver real value and keep growing professionally.",
  "sumSkills": "Strengths include {skills}.",
  "fallbackJob": "professional",
  "verbs": "Led|Built|Launched|Improved|Reduced|Managed|Designed|Achieved|Delivered|Increased",
  "softSkills": "Communication|Teamwork|Problem solving|Time management|Leadership|Adaptability|Critical thinking|Creativity|Attention to detail|Negotiation|Customer service|Project management|Analytical skills|Public speaking",
};
