// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsEs = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Elige tu idioma",
  "myResumes": "Mis currículums",
  "newResume": "Nuevo currículum",
  "noResumes": "Aún no hay currículums",
  "noResumesHint": "Crea tu primer currículum profesional",
  "untitled": "Currículum sin título",
  "personal": "Datos personales",
  "summary": "Resumen",
  "experience": "Experiencia",
  "education": "Educación",
  "skills": "Habilidades",
  "languages": "Idiomas",
  "projects": "Proyectos",
  "design": "Diseño",
  "ai": "IA",
  "preview": "Vista previa y exportar",
  "settings": "Ajustes",
  "uiLanguage": "Idioma de la app",
  "premium": "Premium",
  "cancel": "Cancelar",
  "delete": "Eliminar",
  "duplicate": "Duplicar",
  "confirmDelete": "¿Eliminar este currículum?",
  "add": "Añadir",
  "fullName": "Nombre completo",
  "jobTitle": "Puesto",
  "email": "Correo electrónico",
  "phone": "Teléfono",
  "city": "Ciudad, País",
  "website": "Sitio web o LinkedIn",
  "company": "Empresa",
  "position": "Cargo",
  "location": "Lugar",
  "startDate": "Inicio",
  "endDate": "Fin",
  "present": "Actual",
  "description": "Descripción (una viñeta por línea)",
  "school": "Institución",
  "degree": "Título / Área",
  "level": "Nivel",
  "skillHint": "Añadir habilidad",
  "projectName": "Nombre del proyecto",
  "projectLink": "Enlace",
  "langName": "Idioma",
  "suggestions": "Sugerencias",
  "actionVerbs": "Verbos de acción para empezar",
  "completeness": "Completitud del currículum",
  "missing": "Falta",
  "resumeLanguage": "Idioma del currículum",
  "accent": "Color principal",
  "template": "Plantilla",
  "photo": "Foto",
  "choosePhoto": "Elegir foto",
  "removePhoto": "Quitar foto",
  "premiumTitle": "Plantilla Premium",
  "premiumBody": "Esta plantilla es parte de Premium.",
  "activateDemo": "Activar (demo)",
  "premiumActive": "Premium activo",
  "lv0": "Básico",
  "lv1": "Intermedio",
  "lv2": "Avanzado",
  "lv3": "Fluido",
  "lv4": "Nativo",
  "tpl_classic": "Clásica",
  "tpl_modern": "Moderna",
  "tpl_minimal": "Minimalista",
  "tpl_banner": "Banner",
  "tpl_compact": "Compacta",
  "tpl_executive": "Ejecutiva",
  "resumeName": "Nombre del archivo",
  "about": "Acerca de",
  "free": "Gratis",
  "aiTools": "Herramientas de IA",
  "aiGenerate": "Redactar con IA",
  "aiImprove": "Mejorar con IA",
  "aiBullets": "Sugerir viñetas",
  "aiSkills": "Sugerir habilidades con IA",
  "aiWorking": "Procesando…",
  "aiError": "Falló la solicitud de IA. Inténtalo de nuevo.",
  "apply": "Aplicar",
  "copy": "Copiar",
  "copied": "Copiado",
  "aiOfflineNote": "Modo básico. Conecta un servidor de IA en Ajustes para todas las funciones.",
  "aiQuotaReached": "Límite diario gratuito de IA alcanzado",
  "aiFreeLeft": "Usos gratuitos de IA restantes hoy",
  "aiReview": "Revisar mi currículum",
  "aiReviewHint": "Obtén una puntuación y consejos",
  "aiJobMatch": "Adaptar a un empleo",
  "aiJobHint": "Pega una oferta para ver las palabras clave que faltan",
  "aiJobField": "Descripción del puesto",
  "aiAnalyze": "Analizar",
  "aiCoverLetter": "Carta de presentación",
  "aiCoverHint": "Redacta una carta adaptada al puesto",
  "aiTranslate": "Traducir currículum",
  "aiTranslateHint": "Crea una copia traducida a otro idioma",
  "targetLanguage": "Idioma de destino",
  "aiTranslated": "Copia traducida creada",
  "aiTranslateNeedsServer": "La traducción requiere un servidor de IA. Configúralo en Ajustes.",
  "matchScore": "Coincidencia",
  "matched": "Palabras clave coincidentes",
  "missingKw": "Palabras clave faltantes",
  "aiServer": "Dirección del servidor de IA",
  "aiServerHint": "Déjalo vacío para usar el predeterminado",
  "tips": "Consejos",
  "rvScore": "Puntuación del currículum",
  "rvSummaryShort": "Tu resumen es corto. Apunta a 2 a 4 frases.",
  "rvNoNumbers": "Añade números a tus logros (porcentajes, importes, cantidades).",
  "rvFewSkills": "Incluye al menos 6 habilidades relevantes.",
  "rvNoBullets": "Describe tu experiencia con una viñeta por logro.",
  "rvGood": "Tu currículum se ve sólido.",
  "clTemplate": "Estimado equipo de selección:\n\nMe dirijo a ustedes para postularme al puesto de {job}. Entre mis fortalezas están {skills}, y me encantaría conversar sobre cómo puedo aportar a su equipo.\n\nAtentamente,\n{name}",
  "bulletHint": "añade lo que hiciste y el resultado",
  "editPhoto": "Editar foto",
  "cropHint": "Arrastra y pellizca para recortar",
  "rotate": "Girar",
  "filters": "Filtros",
  "brightness": "Brillo",
  "contrast": "Contraste",
  "saturation": "Saturación",
  "reset": "Restablecer",
  "f_original": "Original",
  "f_bw": "B/N",
  "f_sepia": "Sepia",
  "f_warm": "Cálido",
  "f_cool": "Frío",
  "f_vivid": "Vivo",
  "f_fade": "Desvanecido",
  "pickDate": "Elegir fecha",
  "clear": "Borrar",
  "share": "Compartir",
  "saveFile": "Guardar",
  "saved": "Guardado",
  "saveFailed": "No se pudo guardar el archivo",
  "sumYears": "{job} orientado a resultados con más de {years} años de experiencia, enfocado en generar impacto medible y trabajar en equipo.",
  "sumPlain": "{job} motivado y con gran capacidad de aprendizaje, deseoso de aportar valor y seguir creciendo.",
  "sumSkills": "Fortalezas: {skills}.",
  "fallbackJob": "profesional",
  "verbs": "Lideré|Desarrollé|Lancé|Mejoré|Reduje|Gestioné|Diseñé|Logré|Entregué|Aumenté",
  "softSkills": "Comunicación|Trabajo en equipo|Resolución de problemas|Gestión del tiempo|Liderazgo|Adaptabilidad|Pensamiento crítico|Creatividad|Atención al detalle|Negociación|Atención al cliente|Gestión de proyectos|Capacidad analítica|Hablar en público",
};
