// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsFr = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Choisissez votre langue",
  "myResumes": "Mes CV",
  "newResume": "Nouveau CV",
  "noResumes": "Aucun CV pour le moment",
  "noResumesHint": "Créez votre premier CV professionnel",
  "untitled": "CV sans titre",
  "personal": "Informations personnelles",
  "summary": "Résumé",
  "experience": "Expérience",
  "education": "Formation",
  "skills": "Compétences",
  "languages": "Langues",
  "projects": "Projets",
  "design": "Design",
  "ai": "IA",
  "preview": "Aperçu et export",
  "settings": "Paramètres",
  "uiLanguage": "Langue de l'application",
  "premium": "Premium",
  "cancel": "Annuler",
  "delete": "Supprimer",
  "duplicate": "Dupliquer",
  "confirmDelete": "Supprimer ce CV ?",
  "add": "Ajouter",
  "fullName": "Nom complet",
  "jobTitle": "Poste",
  "email": "E-mail",
  "phone": "Téléphone",
  "city": "Ville, Pays",
  "website": "Site web ou LinkedIn",
  "company": "Entreprise",
  "position": "Intitulé",
  "location": "Lieu",
  "startDate": "Début",
  "endDate": "Fin",
  "present": "Présent",
  "description": "Description (une puce par ligne)",
  "school": "Établissement",
  "degree": "Diplôme / Domaine",
  "level": "Niveau",
  "skillHint": "Ajouter une compétence",
  "projectName": "Nom du projet",
  "projectLink": "Lien",
  "langName": "Langue",
  "suggestions": "Suggestions",
  "actionVerbs": "Verbes d'action pour commencer",
  "completeness": "Complétude du CV",
  "missing": "Manquant",
  "resumeLanguage": "Langue du CV",
  "accent": "Couleur principale",
  "template": "Modèle",
  "photo": "Photo",
  "choosePhoto": "Choisir une photo",
  "removePhoto": "Supprimer la photo",
  "premiumTitle": "Modèle Premium",
  "premiumBody": "Ce modèle fait partie de Premium.",
  "activateDemo": "Activer (démo)",
  "premiumActive": "Premium activé",
  "lv0": "Débutant",
  "lv1": "Intermédiaire",
  "lv2": "Avancé",
  "lv3": "Courant",
  "lv4": "Langue maternelle",
  "tpl_classic": "Classique",
  "tpl_modern": "Moderne",
  "tpl_minimal": "Minimal",
  "tpl_banner": "Bandeau",
  "tpl_compact": "Compact",
  "tpl_executive": "Exécutif",
  "resumeName": "Nom du fichier",
  "about": "À propos",
  "free": "Gratuit",
  "aiTools": "Outils IA",
  "aiGenerate": "Rédiger avec l'IA",
  "aiImprove": "Améliorer avec l'IA",
  "aiBullets": "Suggérer des puces",
  "aiSkills": "Suggérer des compétences avec l'IA",
  "aiWorking": "Traitement…",
  "aiError": "Échec de la requête IA. Réessayez.",
  "apply": "Appliquer",
  "copy": "Copier",
  "copied": "Copié",
  "aiOfflineNote": "Mode de base. Connectez un serveur IA dans les paramètres pour toutes les fonctions.",
  "aiQuotaReached": "Limite quotidienne gratuite d'IA atteinte",
  "aiFreeLeft": "Utilisations IA gratuites restantes aujourd'hui",
  "aiReview": "Analyser mon CV",
  "aiReviewHint": "Obtenez une note et des conseils",
  "aiJobMatch": "Adapter à une offre",
  "aiJobHint": "Collez une offre pour voir les mots-clés manquants",
  "aiJobField": "Description du poste",
  "aiAnalyze": "Analyser",
  "aiCoverLetter": "Lettre de motivation",
  "aiCoverHint": "Rédigez une lettre adaptée à l'offre",
  "aiTranslate": "Traduire le CV",
  "aiTranslateHint": "Créez une copie traduite dans une autre langue",
  "targetLanguage": "Langue cible",
  "aiTranslated": "Copie traduite créée",
  "aiTranslateNeedsServer": "La traduction nécessite un serveur IA. Configurez-le dans les paramètres.",
  "matchScore": "Correspondance",
  "matched": "Mots-clés trouvés",
  "missingKw": "Mots-clés manquants",
  "aiServer": "Adresse du serveur IA",
  "aiServerHint": "Laissez vide pour utiliser la valeur par défaut",
  "tips": "Conseils",
  "rvScore": "Note du CV",
  "rvSummaryShort": "Votre résumé est court. Visez 2 à 4 phrases.",
  "rvNoNumbers": "Ajoutez des chiffres à vos réalisations (pourcentages, montants, volumes).",
  "rvFewSkills": "Listez au moins 6 compétences pertinentes.",
  "rvNoBullets": "Décrivez votre expérience avec une puce par réalisation.",
  "rvGood": "Votre CV a l'air solide.",
  "clTemplate": "Madame, Monsieur,\n\nJe vous écris pour postuler au poste de {job}. Mes points forts incluent {skills}, et je serais ravi(e) d'échanger sur ma contribution à votre équipe.\n\nCordialement,\n{name}",
  "bulletHint": "ajoutez ce que vous avez fait et le résultat",
  "editPhoto": "Modifier la photo",
  "cropHint": "Glissez et pincez pour recadrer",
  "rotate": "Pivoter",
  "filters": "Filtres",
  "brightness": "Luminosité",
  "contrast": "Contraste",
  "saturation": "Saturation",
  "reset": "Réinitialiser",
  "f_original": "Original",
  "f_bw": "N&B",
  "f_sepia": "Sépia",
  "f_warm": "Chaud",
  "f_cool": "Froid",
  "f_vivid": "Éclatant",
  "f_fade": "Délavé",
  "pickDate": "Choisir la date",
  "clear": "Effacer",
  "share": "Partager",
  "saveFile": "Enregistrer",
  "saved": "Enregistré",
  "saveFailed": "Impossible d'enregistrer le fichier",
  "sumYears": "{job} orienté résultats avec plus de {years} ans d'expérience, engagé à produire un impact mesurable et à collaborer efficacement.",
  "sumPlain": "{job} motivé et apprenant rapide, désireux d'apporter une vraie valeur et de progresser.",
  "sumSkills": "Points forts : {skills}.",
  "fallbackJob": "professionnel",
  "verbs": "Dirigé|Développé|Lancé|Amélioré|Réduit|Géré|Conçu|Atteint|Livré|Augmenté",
  "softSkills": "Communication|Travail d'équipe|Résolution de problèmes|Gestion du temps|Leadership|Adaptabilité|Esprit critique|Créativité|Souci du détail|Négociation|Service client|Gestion de projet|Esprit d'analyse|Prise de parole en public",
};
