// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsId = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Pilih bahasa Anda",
  "myResumes": "CV saya",
  "newResume": "CV baru",
  "noResumes": "Belum ada CV",
  "noResumesHint": "Buat CV profesional pertama Anda",
  "untitled": "CV tanpa judul",
  "personal": "Data pribadi",
  "summary": "Ringkasan",
  "experience": "Pengalaman",
  "education": "Pendidikan",
  "skills": "Keahlian",
  "languages": "Bahasa",
  "projects": "Proyek",
  "design": "Desain",
  "ai": "AI",
  "preview": "Pratinjau & ekspor",
  "settings": "Pengaturan",
  "uiLanguage": "Bahasa aplikasi",
  "premium": "Premium",
  "cancel": "Batal",
  "delete": "Hapus",
  "duplicate": "Duplikat",
  "confirmDelete": "Hapus CV ini?",
  "add": "Tambah",
  "fullName": "Nama lengkap",
  "jobTitle": "Jabatan",
  "email": "Email",
  "phone": "Telepon",
  "city": "Kota, Negara",
  "website": "Situs web atau LinkedIn",
  "company": "Perusahaan",
  "position": "Posisi",
  "location": "Lokasi",
  "startDate": "Mulai",
  "endDate": "Selesai",
  "present": "Sekarang",
  "description": "Deskripsi (satu poin per baris)",
  "school": "Institusi",
  "degree": "Gelar / Jurusan",
  "level": "Tingkat",
  "skillHint": "Tambah keahlian",
  "projectName": "Nama proyek",
  "projectLink": "Tautan",
  "langName": "Bahasa",
  "suggestions": "Saran",
  "actionVerbs": "Kata kerja kuat untuk memulai",
  "completeness": "Kelengkapan CV",
  "missing": "Belum ada",
  "resumeLanguage": "Bahasa CV",
  "accent": "Warna aksen",
  "template": "Templat",
  "photo": "Foto",
  "choosePhoto": "Pilih foto",
  "removePhoto": "Hapus foto",
  "premiumTitle": "Templat Premium",
  "premiumBody": "Templat ini termasuk Premium.",
  "activateDemo": "Aktifkan (demo)",
  "premiumActive": "Premium aktif",
  "lv0": "Dasar",
  "lv1": "Menengah",
  "lv2": "Mahir",
  "lv3": "Fasih",
  "lv4": "Bahasa ibu",
  "tpl_classic": "Klasik",
  "tpl_modern": "Modern",
  "tpl_minimal": "Minimalis",
  "tpl_banner": "Banner",
  "tpl_compact": "Ringkas",
  "tpl_executive": "Eksekutif",
  "resumeName": "Nama file",
  "about": "Tentang",
  "free": "Gratis",
  "aiTools": "Alat AI",
  "aiGenerate": "Tulis dengan AI",
  "aiImprove": "Tingkatkan dengan AI",
  "aiBullets": "Sarankan poin-poin",
  "aiSkills": "Sarankan keahlian dengan AI",
  "aiWorking": "Memproses…",
  "aiError": "Permintaan AI gagal. Coba lagi.",
  "apply": "Terapkan",
  "copy": "Salin",
  "copied": "Tersalin",
  "aiOfflineNote": "Mode dasar. Hubungkan server AI di Pengaturan untuk fitur lengkap.",
  "aiQuotaReached": "Batas harian AI gratis tercapai",
  "aiFreeLeft": "Sisa penggunaan AI gratis hari ini",
  "aiReview": "Tinjau CV saya",
  "aiReviewHint": "Dapatkan skor dan tips perbaikan",
  "aiJobMatch": "Cocokkan dengan lowongan",
  "aiJobHint": "Tempel deskripsi lowongan untuk melihat kata kunci yang kurang",
  "aiJobField": "Deskripsi pekerjaan",
  "aiAnalyze": "Analisis",
  "aiCoverLetter": "Surat lamaran",
  "aiCoverHint": "Tulis surat lamaran yang disesuaikan",
  "aiTranslate": "Terjemahkan CV",
  "aiTranslateHint": "Buat salinan terjemahan dalam bahasa lain",
  "targetLanguage": "Bahasa tujuan",
  "aiTranslated": "Salinan terjemahan dibuat",
  "aiTranslateNeedsServer": "Terjemahan memerlukan server AI. Atur di Pengaturan.",
  "matchScore": "Kecocokan",
  "matched": "Kata kunci cocok",
  "missingKw": "Kata kunci kurang",
  "aiServer": "Alamat server AI",
  "aiServerHint": "Kosongkan untuk memakai bawaan",
  "tips": "Tips",
  "rvScore": "Skor CV",
  "rvSummaryShort": "Ringkasan Anda terlalu pendek. Targetkan 2 sampai 4 kalimat.",
  "rvNoNumbers": "Tambahkan angka pada pencapaian Anda (persentase, jumlah, nominal).",
  "rvFewSkills": "Cantumkan minimal 6 keahlian yang relevan.",
  "rvNoBullets": "Jelaskan pengalaman dengan satu poin per pencapaian.",
  "rvGood": "CV Anda terlihat kuat.",
  "clTemplate": "Yth. Bapak/Ibu Manajer Rekrutmen,\n\nSaya bermaksud melamar posisi {job}. Kekuatan saya antara lain {skills}, dan saya berharap dapat berdiskusi tentang kontribusi yang bisa saya berikan kepada tim Anda.\n\nHormat saya,\n{name}",
  "bulletHint": "tambahkan apa yang Anda lakukan dan hasilnya",
  "editPhoto": "Edit foto",
  "cropHint": "Geser dan cubit untuk memotong",
  "rotate": "Putar",
  "filters": "Filter",
  "brightness": "Kecerahan",
  "contrast": "Kontras",
  "saturation": "Saturasi",
  "reset": "Atur ulang",
  "f_original": "Asli",
  "f_bw": "Hitam putih",
  "f_sepia": "Sepia",
  "f_warm": "Hangat",
  "f_cool": "Dingin",
  "f_vivid": "Tajam",
  "f_fade": "Pudar",
  "pickDate": "Pilih tanggal",
  "clear": "Hapus",
  "share": "Bagikan",
  "saveFile": "Simpan",
  "saved": "Tersimpan",
  "saveFailed": "Gagal menyimpan file",
  "sumYears": "{job} berorientasi hasil dengan pengalaman lebih dari {years} tahun, fokus pada dampak terukur dan kerja sama tim.",
  "sumPlain": "{job} yang termotivasi dan cepat belajar, siap memberi nilai nyata dan terus berkembang secara profesional.",
  "sumSkills": "Kekuatan: {skills}.",
  "fallbackJob": "profesional",
  "verbs": "Memimpin|Membangun|Meluncurkan|Meningkatkan|Mengurangi|Mengelola|Merancang|Mencapai|Menyelesaikan|Menambah",
  "softSkills": "Komunikasi|Kerja sama tim|Pemecahan masalah|Manajemen waktu|Kepemimpinan|Adaptabilitas|Berpikir kritis|Kreativitas|Ketelitian|Negosiasi|Layanan pelanggan|Manajemen proyek|Kemampuan analitis|Berbicara di depan umum",
};
