// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsIt = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Scegli la tua lingua",
  "myResumes": "I miei CV",
  "newResume": "Nuovo CV",
  "noResumes": "Ancora nessun CV",
  "noResumesHint": "Crea il tuo primo CV professionale",
  "untitled": "CV senza titolo",
  "personal": "Dati personali",
  "summary": "Profilo",
  "experience": "Esperienza",
  "education": "Istruzione",
  "skills": "Competenze",
  "languages": "Lingue",
  "projects": "Progetti",
  "design": "Design",
  "ai": "IA",
  "preview": "Anteprima ed esportazione",
  "settings": "Impostazioni",
  "uiLanguage": "Lingua dell'app",
  "premium": "Premium",
  "cancel": "Annulla",
  "delete": "Elimina",
  "duplicate": "Duplica",
  "confirmDelete": "Eliminare questo CV?",
  "add": "Aggiungi",
  "fullName": "Nome completo",
  "jobTitle": "Qualifica",
  "email": "E-mail",
  "phone": "Telefono",
  "city": "Città, Paese",
  "website": "Sito web o LinkedIn",
  "company": "Azienda",
  "position": "Ruolo",
  "location": "Luogo",
  "startDate": "Inizio",
  "endDate": "Fine",
  "present": "In corso",
  "description": "Descrizione (un elenco puntato per riga)",
  "school": "Istituto",
  "degree": "Titolo / Corso",
  "level": "Livello",
  "skillHint": "Aggiungi una competenza",
  "projectName": "Nome del progetto",
  "projectLink": "Link",
  "langName": "Lingua",
  "suggestions": "Suggerimenti",
  "actionVerbs": "Verbi d'azione con cui iniziare",
  "completeness": "Completezza del CV",
  "missing": "Mancano",
  "resumeLanguage": "Lingua del CV",
  "accent": "Colore principale",
  "template": "Modello",
  "photo": "Foto",
  "choosePhoto": "Scegli foto",
  "removePhoto": "Rimuovi foto",
  "premiumTitle": "Modello Premium",
  "premiumBody": "Questo modello fa parte di Premium.",
  "activateDemo": "Attiva (demo)",
  "premiumActive": "Premium attivo",
  "lv0": "Base",
  "lv1": "Intermedio",
  "lv2": "Avanzato",
  "lv3": "Fluente",
  "lv4": "Madrelingua",
  "tpl_classic": "Classico",
  "tpl_modern": "Moderno",
  "tpl_minimal": "Minimale",
  "tpl_banner": "Banner",
  "tpl_compact": "Compatto",
  "tpl_executive": "Executive",
  "resumeName": "Nome del file",
  "about": "Informazioni",
  "free": "Gratis",
  "aiTools": "Strumenti IA",
  "aiGenerate": "Scrivi con l'IA",
  "aiImprove": "Migliora con l'IA",
  "aiBullets": "Suggerisci elenchi puntati",
  "aiSkills": "Suggerisci competenze con l'IA",
  "aiWorking": "Elaborazione…",
  "aiError": "Richiesta IA non riuscita. Riprova.",
  "apply": "Applica",
  "copy": "Copia",
  "copied": "Copiato",
  "aiOfflineNote": "Modalità base. Collega un server IA nelle Impostazioni per tutte le funzioni.",
  "aiQuotaReached": "Limite giornaliero gratuito di IA raggiunto",
  "aiFreeLeft": "Usi IA gratuiti rimasti oggi",
  "aiReview": "Analizza il mio CV",
  "aiReviewHint": "Ottieni un punteggio e consigli",
  "aiJobMatch": "Confronta con un'offerta",
  "aiJobHint": "Incolla un'offerta per vedere le parole chiave mancanti",
  "aiJobField": "Descrizione del lavoro",
  "aiAnalyze": "Analizza",
  "aiCoverLetter": "Lettera di presentazione",
  "aiCoverHint": "Scrivi una lettera su misura per l'offerta",
  "aiTranslate": "Traduci il CV",
  "aiTranslateHint": "Crea una copia tradotta in un'altra lingua",
  "targetLanguage": "Lingua di destinazione",
  "aiTranslated": "Copia tradotta creata",
  "aiTranslateNeedsServer": "La traduzione richiede un server IA. Configuralo nelle Impostazioni.",
  "matchScore": "Corrispondenza",
  "matched": "Parole chiave trovate",
  "missingKw": "Parole chiave mancanti",
  "aiServer": "Indirizzo del server IA",
  "aiServerHint": "Lascia vuoto per usare quello predefinito",
  "tips": "Consigli",
  "rvScore": "Punteggio del CV",
  "rvSummaryShort": "Il tuo profilo è breve. Punta a 2-4 frasi.",
  "rvNoNumbers": "Aggiungi numeri ai tuoi risultati (percentuali, importi, quantità).",
  "rvFewSkills": "Elenca almeno 6 competenze pertinenti.",
  "rvNoBullets": "Descrivi l'esperienza con un punto elenco per risultato.",
  "rvGood": "Il tuo CV appare solido.",
  "clTemplate": "Gentile Responsabile delle Risorse Umane,\n\nvi scrivo per candidarmi alla posizione di {job}. Tra i miei punti di forza: {skills}. Sarei lieto/a di discutere di come posso contribuire al vostro team.\n\nCordiali saluti,\n{name}",
  "bulletHint": "aggiungi cosa hai fatto e il risultato",
  "editPhoto": "Modifica foto",
  "cropHint": "Trascina e pizzica per ritagliare",
  "rotate": "Ruota",
  "filters": "Filtri",
  "brightness": "Luminosità",
  "contrast": "Contrasto",
  "saturation": "Saturazione",
  "reset": "Ripristina",
  "f_original": "Originale",
  "f_bw": "B/N",
  "f_sepia": "Seppia",
  "f_warm": "Caldo",
  "f_cool": "Freddo",
  "f_vivid": "Vivido",
  "f_fade": "Sbiadito",
  "pickDate": "Scegli la data",
  "clear": "Cancella",
  "share": "Condividi",
  "saveFile": "Salva",
  "saved": "Salvato",
  "saveFailed": "Impossibile salvare il file",
  "sumYears": "{job} orientato ai risultati con oltre {years} anni di esperienza, concentrato su un impatto misurabile e sul lavoro di squadra.",
  "sumPlain": "{job} motivato e rapido nell'apprendimento, desideroso di creare valore e crescere professionalmente.",
  "sumSkills": "Punti di forza: {skills}.",
  "fallbackJob": "professionista",
  "verbs": "Guidato|Sviluppato|Lanciato|Migliorato|Ridotto|Gestito|Progettato|Raggiunto|Consegnato|Aumentato",
  "softSkills": "Comunicazione|Lavoro di squadra|Problem solving|Gestione del tempo|Leadership|Adattabilità|Pensiero critico|Creatività|Attenzione ai dettagli|Negoziazione|Assistenza clienti|Gestione dei progetti|Capacità analitiche|Public speaking",
};
