// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsNb = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Velg språk",
  "myResumes": "Mine CV-er",
  "newResume": "Ny CV",
  "noResumes": "Ingen CV-er ennå",
  "noResumesHint": "Lag din første profesjonelle CV",
  "untitled": "CV uten navn",
  "personal": "Personlig informasjon",
  "summary": "Profil",
  "experience": "Erfaring",
  "education": "Utdanning",
  "skills": "Ferdigheter",
  "languages": "Språk",
  "projects": "Prosjekter",
  "design": "Design",
  "ai": "KI",
  "preview": "Forhåndsvisning og eksport",
  "settings": "Innstillinger",
  "uiLanguage": "Appspråk",
  "premium": "Premium",
  "cancel": "Avbryt",
  "delete": "Slett",
  "duplicate": "Dupliser",
  "confirmDelete": "Slette denne CV-en?",
  "add": "Legg til",
  "fullName": "Fullt navn",
  "jobTitle": "Stillingstittel",
  "email": "E-post",
  "phone": "Telefon",
  "city": "By, land",
  "website": "Nettside eller LinkedIn",
  "company": "Bedrift",
  "position": "Stilling",
  "location": "Sted",
  "startDate": "Start",
  "endDate": "Slutt",
  "present": "Nå",
  "description": "Beskrivelse (ett punkt per linje)",
  "school": "Skole",
  "degree": "Grad / Fag",
  "level": "Nivå",
  "skillHint": "Legg til ferdighet",
  "projectName": "Prosjektnavn",
  "projectLink": "Lenke",
  "langName": "Språk",
  "suggestions": "Forslag",
  "actionVerbs": "Sterke verb å starte med",
  "completeness": "CV-ens fullstendighet",
  "missing": "Mangler",
  "resumeLanguage": "CV-språk",
  "accent": "Aksentfarge",
  "template": "Mal",
  "photo": "Bilde",
  "choosePhoto": "Velg bilde",
  "removePhoto": "Fjern bilde",
  "premiumTitle": "Premium-mal",
  "premiumBody": "Denne malen er en del av Premium.",
  "activateDemo": "Aktiver (demo)",
  "premiumActive": "Premium er aktiv",
  "lv0": "Grunnleggende",
  "lv1": "Middels",
  "lv2": "Avansert",
  "lv3": "Flytende",
  "lv4": "Morsmål",
  "tpl_classic": "Klassisk",
  "tpl_modern": "Moderne",
  "tpl_minimal": "Minimalistisk",
  "tpl_banner": "Banner",
  "tpl_compact": "Kompakt",
  "tpl_executive": "Executive",
  "resumeName": "Filnavn",
  "about": "Om",
  "free": "Gratis",
  "aiTools": "KI-verktøy",
  "aiGenerate": "Skriv med KI",
  "aiImprove": "Forbedre med KI",
  "aiBullets": "Foreslå punkter",
  "aiSkills": "Foreslå ferdigheter med KI",
  "aiWorking": "Jobber…",
  "aiError": "KI-forespørselen mislyktes. Prøv igjen.",
  "apply": "Bruk",
  "copy": "Kopier",
  "copied": "Kopiert",
  "aiOfflineNote": "Grunnmodus. Koble til en KI-server i Innstillinger for full funksjonalitet.",
  "aiQuotaReached": "Daglig gratisgrense for KI er nådd",
  "aiFreeLeft": "Gjenstående gratis KI-bruk i dag",
  "aiReview": "Gjennomgå CV-en min",
  "aiReviewHint": "Få en poengsum og forbedringstips",
  "aiJobMatch": "Tilpass til en stilling",
  "aiJobHint": "Lim inn en stillingsannonse for å se manglende nøkkelord",
  "aiJobField": "Stillingsbeskrivelse",
  "aiAnalyze": "Analyser",
  "aiCoverLetter": "Søknadsbrev",
  "aiCoverHint": "Skriv et tilpasset søknadsbrev",
  "aiTranslate": "Oversett CV",
  "aiTranslateHint": "Lag en oversatt kopi på et annet språk",
  "targetLanguage": "Målspråk",
  "aiTranslated": "Oversatt kopi opprettet",
  "aiTranslateNeedsServer": "Oversettelse krever en KI-server. Sett den opp i Innstillinger.",
  "matchScore": "Samsvar",
  "matched": "Samsvarende nøkkelord",
  "missingKw": "Manglende nøkkelord",
  "aiServer": "Adresse til KI-server",
  "aiServerHint": "La stå tomt for å bruke standard",
  "tips": "Tips",
  "rvScore": "CV-poengsum",
  "rvSummaryShort": "Profilen din er kort. Sikt mot 2 til 4 setninger.",
  "rvNoNumbers": "Legg til tall i resultatene dine (prosent, beløp, antall).",
  "rvFewSkills": "List opp minst 6 relevante ferdigheter.",
  "rvNoBullets": "Beskriv erfaringen med ett punkt per resultat.",
  "rvGood": "CV-en din ser sterk ut.",
  "clTemplate": "Til rette vedkommende,\n\nJeg søker på stillingen som {job}. Mine styrker inkluderer {skills}, og jeg ville satt pris på en samtale om hvordan jeg kan bidra til teamet deres.\n\nMed vennlig hilsen\n{name}",
  "bulletHint": "legg til hva du gjorde og resultatet",
  "editPhoto": "Rediger bilde",
  "cropHint": "Dra og knip for å beskjære",
  "rotate": "Roter",
  "filters": "Filtre",
  "brightness": "Lysstyrke",
  "contrast": "Kontrast",
  "saturation": "Metning",
  "reset": "Tilbakestill",
  "f_original": "Original",
  "f_bw": "S/H",
  "f_sepia": "Sepia",
  "f_warm": "Varm",
  "f_cool": "Kald",
  "f_vivid": "Livlig",
  "f_fade": "Falmet",
  "pickDate": "Velg dato",
  "clear": "Tøm",
  "share": "Del",
  "saveFile": "Lagre",
  "saved": "Lagret",
  "saveFailed": "Kunne ikke lagre filen",
  "sumYears": "Resultatorientert {job} med over {years} års erfaring, opptatt av målbar effekt og samarbeid.",
  "sumPlain": "Motivert {job} som lærer raskt og vil skape reell verdi og utvikle seg videre.",
  "sumSkills": "Styrker: {skills}.",
  "fallbackJob": "fagperson",
  "verbs": "Ledet|Bygget|Lanserte|Forbedret|Reduserte|Administrerte|Utformet|Oppnådde|Leverte|Økte",
  "softSkills": "Kommunikasjon|Samarbeid|Problemløsning|Tidsstyring|Ledelse|Tilpasningsevne|Kritisk tenkning|Kreativitet|Nøyaktighet|Forhandling|Kundeservice|Prosjektledelse|Analytiske ferdigheter|Presentasjonsteknikk",
};
