// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsNl = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Kies je taal",
  "myResumes": "Mijn cv's",
  "newResume": "Nieuw cv",
  "noResumes": "Nog geen cv's",
  "noResumesHint": "Maak je eerste professionele cv",
  "untitled": "Naamloos cv",
  "personal": "Persoonlijke gegevens",
  "summary": "Profiel",
  "experience": "Werkervaring",
  "education": "Opleiding",
  "skills": "Vaardigheden",
  "languages": "Talen",
  "projects": "Projecten",
  "design": "Ontwerp",
  "ai": "AI",
  "preview": "Voorbeeld en export",
  "settings": "Instellingen",
  "uiLanguage": "App-taal",
  "premium": "Premium",
  "cancel": "Annuleren",
  "delete": "Verwijderen",
  "duplicate": "Dupliceren",
  "confirmDelete": "Dit cv verwijderen?",
  "add": "Toevoegen",
  "fullName": "Volledige naam",
  "jobTitle": "Functietitel",
  "email": "E-mail",
  "phone": "Telefoon",
  "city": "Plaats, land",
  "website": "Website of LinkedIn",
  "company": "Bedrijf",
  "position": "Functie",
  "location": "Locatie",
  "startDate": "Start",
  "endDate": "Einde",
  "present": "Heden",
  "description": "Beschrijving (één opsommingsteken per regel)",
  "school": "Onderwijsinstelling",
  "degree": "Diploma / Richting",
  "level": "Niveau",
  "skillHint": "Vaardigheid toevoegen",
  "projectName": "Projectnaam",
  "projectLink": "Link",
  "langName": "Taal",
  "suggestions": "Suggesties",
  "actionVerbs": "Sterke werkwoorden om mee te beginnen",
  "completeness": "Volledigheid van het cv",
  "missing": "Ontbreekt",
  "resumeLanguage": "Taal van het cv",
  "accent": "Accentkleur",
  "template": "Sjabloon",
  "photo": "Foto",
  "choosePhoto": "Foto kiezen",
  "removePhoto": "Foto verwijderen",
  "premiumTitle": "Premium-sjabloon",
  "premiumBody": "Dit sjabloon hoort bij Premium.",
  "activateDemo": "Activeren (demo)",
  "premiumActive": "Premium is actief",
  "lv0": "Basis",
  "lv1": "Gemiddeld",
  "lv2": "Gevorderd",
  "lv3": "Vloeiend",
  "lv4": "Moedertaal",
  "tpl_classic": "Klassiek",
  "tpl_modern": "Modern",
  "tpl_minimal": "Minimalistisch",
  "tpl_banner": "Banner",
  "tpl_compact": "Compact",
  "tpl_executive": "Executive",
  "resumeName": "Bestandsnaam",
  "about": "Over",
  "free": "Gratis",
  "aiTools": "AI-hulpmiddelen",
  "aiGenerate": "Schrijven met AI",
  "aiImprove": "Verbeteren met AI",
  "aiBullets": "Opsommingen voorstellen",
  "aiSkills": "Vaardigheden voorstellen met AI",
  "aiWorking": "Bezig…",
  "aiError": "AI-verzoek mislukt. Probeer het opnieuw.",
  "apply": "Toepassen",
  "copy": "Kopiëren",
  "copied": "Gekopieerd",
  "aiOfflineNote": "Basismodus. Koppel een AI-server in Instellingen voor alle functies.",
  "aiQuotaReached": "Dagelijkse gratis AI-limiet bereikt",
  "aiFreeLeft": "Resterende gratis AI-gebruiken vandaag",
  "aiReview": "Mijn cv beoordelen",
  "aiReviewHint": "Krijg een score en verbetertips",
  "aiJobMatch": "Afstemmen op een vacature",
  "aiJobHint": "Plak een vacaturetekst om ontbrekende trefwoorden te zien",
  "aiJobField": "Functieomschrijving",
  "aiAnalyze": "Analyseren",
  "aiCoverLetter": "Sollicitatiebrief",
  "aiCoverHint": "Schrijf een brief op maat voor de vacature",
  "aiTranslate": "Cv vertalen",
  "aiTranslateHint": "Maak een vertaalde kopie in een andere taal",
  "targetLanguage": "Doeltaal",
  "aiTranslated": "Vertaalde kopie gemaakt",
  "aiTranslateNeedsServer": "Vertalen vereist een AI-server. Stel die in bij Instellingen.",
  "matchScore": "Overeenkomst",
  "matched": "Gevonden trefwoorden",
  "missingKw": "Ontbrekende trefwoorden",
  "aiServer": "Adres van AI-server",
  "aiServerHint": "Laat leeg voor de standaardwaarde",
  "tips": "Tips",
  "rvScore": "Cv-score",
  "rvSummaryShort": "Je profiel is kort. Streef naar 2 tot 4 zinnen.",
  "rvNoNumbers": "Voeg cijfers toe aan je prestaties (percentages, bedragen, aantallen).",
  "rvFewSkills": "Noem minstens 6 relevante vaardigheden.",
  "rvNoBullets": "Beschrijf je ervaring met één opsommingsteken per prestatie.",
  "rvGood": "Je cv ziet er sterk uit.",
  "clTemplate": "Geachte heer/mevrouw,\n\nHierbij solliciteer ik naar de functie van {job}. Tot mijn sterke punten behoren {skills}, en ik bespreek graag hoe ik uw team kan versterken.\n\nMet vriendelijke groet,\n{name}",
  "bulletHint": "voeg toe wat je deed en het resultaat",
  "editPhoto": "Foto bewerken",
  "cropHint": "Sleep en knijp om bij te snijden",
  "rotate": "Draaien",
  "filters": "Filters",
  "brightness": "Helderheid",
  "contrast": "Contrast",
  "saturation": "Verzadiging",
  "reset": "Herstellen",
  "f_original": "Origineel",
  "f_bw": "Zwart-wit",
  "f_sepia": "Sepia",
  "f_warm": "Warm",
  "f_cool": "Koel",
  "f_vivid": "Levendig",
  "f_fade": "Vervaagd",
  "pickDate": "Datum kiezen",
  "clear": "Wissen",
  "share": "Delen",
  "saveFile": "Opslaan",
  "saved": "Opgeslagen",
  "saveFailed": "Bestand kon niet worden opgeslagen",
  "sumYears": "Resultaatgerichte {job} met meer dan {years} jaar ervaring, gericht op meetbare impact en samenwerking.",
  "sumPlain": "Gemotiveerde {job} die snel leert en echte meerwaarde wil leveren en zich wil blijven ontwikkelen.",
  "sumSkills": "Sterke punten: {skills}.",
  "fallbackJob": "professional",
  "verbs": "Geleid|Ontwikkeld|Gelanceerd|Verbeterd|Verminderd|Beheerd|Ontworpen|Behaald|Opgeleverd|Verhoogd",
  "softSkills": "Communicatie|Teamwork|Probleemoplossing|Tijdmanagement|Leiderschap|Aanpassingsvermogen|Kritisch denken|Creativiteit|Oog voor detail|Onderhandelen|Klantenservice|Projectmanagement|Analytisch vermogen|Presenteren",
};
