// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsPl = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Wybierz język",
  "myResumes": "Moje CV",
  "newResume": "Nowe CV",
  "noResumes": "Brak CV",
  "noResumesHint": "Stwórz swoje pierwsze profesjonalne CV",
  "untitled": "CV bez nazwy",
  "personal": "Dane osobowe",
  "summary": "Podsumowanie",
  "experience": "Doświadczenie",
  "education": "Wykształcenie",
  "skills": "Umiejętności",
  "languages": "Języki",
  "projects": "Projekty",
  "design": "Wygląd",
  "ai": "AI",
  "preview": "Podgląd i eksport",
  "settings": "Ustawienia",
  "uiLanguage": "Język aplikacji",
  "premium": "Premium",
  "cancel": "Anuluj",
  "delete": "Usuń",
  "duplicate": "Duplikuj",
  "confirmDelete": "Usunąć to CV?",
  "add": "Dodaj",
  "fullName": "Imię i nazwisko",
  "jobTitle": "Stanowisko",
  "email": "E-mail",
  "phone": "Telefon",
  "city": "Miasto, kraj",
  "website": "Strona WWW lub LinkedIn",
  "company": "Firma",
  "position": "Stanowisko",
  "location": "Miejsce",
  "startDate": "Początek",
  "endDate": "Koniec",
  "present": "Obecnie",
  "description": "Opis (jeden punkt w wierszu)",
  "school": "Uczelnia / szkoła",
  "degree": "Tytuł / kierunek",
  "level": "Poziom",
  "skillHint": "Dodaj umiejętność",
  "projectName": "Nazwa projektu",
  "projectLink": "Link",
  "langName": "Język",
  "suggestions": "Sugestie",
  "actionVerbs": "Mocne czasowniki na początek",
  "completeness": "Kompletność CV",
  "missing": "Brakuje",
  "resumeLanguage": "Język CV",
  "accent": "Kolor wiodący",
  "template": "Szablon",
  "photo": "Zdjęcie",
  "choosePhoto": "Wybierz zdjęcie",
  "removePhoto": "Usuń zdjęcie",
  "premiumTitle": "Szablon Premium",
  "premiumBody": "Ten szablon jest częścią Premium.",
  "activateDemo": "Aktywuj (demo)",
  "premiumActive": "Premium jest aktywne",
  "lv0": "Podstawowy",
  "lv1": "Średniozaawansowany",
  "lv2": "Zaawansowany",
  "lv3": "Biegły",
  "lv4": "Ojczysty",
  "tpl_classic": "Klasyczny",
  "tpl_modern": "Nowoczesny",
  "tpl_minimal": "Minimalistyczny",
  "tpl_banner": "Baner",
  "tpl_compact": "Kompaktowy",
  "tpl_executive": "Executive",
  "resumeName": "Nazwa pliku",
  "about": "O aplikacji",
  "free": "Za darmo",
  "aiTools": "Narzędzia AI",
  "aiGenerate": "Napisz z AI",
  "aiImprove": "Ulepsz z AI",
  "aiBullets": "Zaproponuj punkty",
  "aiSkills": "Zaproponuj umiejętności z AI",
  "aiWorking": "Przetwarzanie…",
  "aiError": "Zapytanie do AI nie powiodło się. Spróbuj ponownie.",
  "apply": "Zastosuj",
  "copy": "Kopiuj",
  "copied": "Skopiowano",
  "aiOfflineNote": "Tryb podstawowy. Połącz serwer AI w Ustawieniach, aby korzystać ze wszystkich funkcji.",
  "aiQuotaReached": "Osiągnięto dzienny darmowy limit AI",
  "aiFreeLeft": "Pozostałe darmowe użycia AI dzisiaj",
  "aiReview": "Oceń moje CV",
  "aiReviewHint": "Otrzymaj ocenę i wskazówki",
  "aiJobMatch": "Dopasuj do oferty",
  "aiJobHint": "Wklej ofertę pracy, aby zobaczyć brakujące słowa kluczowe",
  "aiJobField": "Opis stanowiska",
  "aiAnalyze": "Analizuj",
  "aiCoverLetter": "List motywacyjny",
  "aiCoverHint": "Napisz list dopasowany do oferty",
  "aiTranslate": "Przetłumacz CV",
  "aiTranslateHint": "Utwórz przetłumaczoną kopię w innym języku",
  "targetLanguage": "Język docelowy",
  "aiTranslated": "Utworzono przetłumaczoną kopię",
  "aiTranslateNeedsServer": "Tłumaczenie wymaga serwera AI. Skonfiguruj go w Ustawieniach.",
  "matchScore": "Dopasowanie",
  "matched": "Znalezione słowa kluczowe",
  "missingKw": "Brakujące słowa kluczowe",
  "aiServer": "Adres serwera AI",
  "aiServerHint": "Zostaw puste, aby użyć domyślnego",
  "tips": "Wskazówki",
  "rvScore": "Ocena CV",
  "rvSummaryShort": "Twoje podsumowanie jest krótkie. Celuj w 2-4 zdania.",
  "rvNoNumbers": "Dodaj liczby do swoich osiągnięć (procenty, kwoty, ilości).",
  "rvFewSkills": "Wymień co najmniej 6 istotnych umiejętności.",
  "rvNoBullets": "Opisz doświadczenie jednym punktem na osiągnięcie.",
  "rvGood": "Twoje CV wygląda solidnie.",
  "clTemplate": "Szanowni Państwo,\n\nz przyjemnością aplikuję na stanowisko {job}. Do moich mocnych stron należą: {skills}. Chętnie porozmawiam o tym, jak mogę wesprzeć Państwa zespół.\n\nZ poważaniem,\n{name}",
  "bulletHint": "dodaj, co zrobiłeś/aś i jaki był efekt",
  "editPhoto": "Edytuj zdjęcie",
  "cropHint": "Przeciągnij i uszczypnij, aby przyciąć",
  "rotate": "Obróć",
  "filters": "Filtry",
  "brightness": "Jasność",
  "contrast": "Kontrast",
  "saturation": "Nasycenie",
  "reset": "Resetuj",
  "f_original": "Oryginał",
  "f_bw": "Czarno-biały",
  "f_sepia": "Sepia",
  "f_warm": "Ciepły",
  "f_cool": "Zimny",
  "f_vivid": "Intensywny",
  "f_fade": "Wyblakły",
  "pickDate": "Wybierz datę",
  "clear": "Wyczyść",
  "share": "Udostępnij",
  "saveFile": "Zapisz",
  "saved": "Zapisano",
  "saveFailed": "Nie udało się zapisać pliku",
  "sumYears": "{job} zorientowany na wyniki, z ponad {years}-letnim doświadczeniem, skupiony na mierzalnych efektach i współpracy w zespole.",
  "sumPlain": "Zmotywowany {job}, szybko się uczy, chce tworzyć realną wartość i stale się rozwijać.",
  "sumSkills": "Mocne strony: {skills}.",
  "fallbackJob": "specjalista",
  "verbs": "Kierowałem|Stworzyłem|Wdrożyłem|Usprawniłem|Zredukowałem|Zarządzałem|Zaprojektowałem|Osiągnąłem|Dostarczyłem|Zwiększyłem",
  "softSkills": "Komunikacja|Praca zespołowa|Rozwiązywanie problemów|Zarządzanie czasem|Przywództwo|Zdolność adaptacji|Krytyczne myślenie|Kreatywność|Dbałość o szczegóły|Negocjacje|Obsługa klienta|Zarządzanie projektami|Myślenie analityczne|Wystąpienia publiczne",
};
