// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsPt = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Escolha o seu idioma",
  "myResumes": "Os meus currículos",
  "newResume": "Novo currículo",
  "noResumes": "Ainda sem currículos",
  "noResumesHint": "Crie o seu primeiro currículo profissional",
  "untitled": "Currículo sem título",
  "personal": "Dados pessoais",
  "summary": "Resumo",
  "experience": "Experiência",
  "education": "Formação",
  "skills": "Competências",
  "languages": "Idiomas",
  "projects": "Projetos",
  "design": "Design",
  "ai": "IA",
  "preview": "Pré-visualização e exportação",
  "settings": "Definições",
  "uiLanguage": "Idioma da aplicação",
  "premium": "Premium",
  "cancel": "Cancelar",
  "delete": "Eliminar",
  "duplicate": "Duplicar",
  "confirmDelete": "Eliminar este currículo?",
  "add": "Adicionar",
  "fullName": "Nome completo",
  "jobTitle": "Cargo",
  "email": "E-mail",
  "phone": "Telefone",
  "city": "Cidade, País",
  "website": "Site ou LinkedIn",
  "company": "Empresa",
  "position": "Função",
  "location": "Local",
  "startDate": "Início",
  "endDate": "Fim",
  "present": "Atual",
  "description": "Descrição (um marcador por linha)",
  "school": "Instituição",
  "degree": "Grau / Área",
  "level": "Nível",
  "skillHint": "Adicionar competência",
  "projectName": "Nome do projeto",
  "projectLink": "Ligação",
  "langName": "Idioma",
  "suggestions": "Sugestões",
  "actionVerbs": "Verbos de ação para começar",
  "completeness": "Completude do currículo",
  "missing": "Em falta",
  "resumeLanguage": "Idioma do currículo",
  "accent": "Cor de destaque",
  "template": "Modelo",
  "photo": "Fotografia",
  "choosePhoto": "Escolher fotografia",
  "removePhoto": "Remover fotografia",
  "premiumTitle": "Modelo Premium",
  "premiumBody": "Este modelo faz parte do Premium.",
  "activateDemo": "Ativar (demo)",
  "premiumActive": "Premium ativo",
  "lv0": "Básico",
  "lv1": "Intermédio",
  "lv2": "Avançado",
  "lv3": "Fluente",
  "lv4": "Nativo",
  "tpl_classic": "Clássico",
  "tpl_modern": "Moderno",
  "tpl_minimal": "Minimalista",
  "tpl_banner": "Banner",
  "tpl_compact": "Compacto",
  "tpl_executive": "Executivo",
  "resumeName": "Nome do ficheiro",
  "about": "Acerca de",
  "free": "Grátis",
  "aiTools": "Ferramentas de IA",
  "aiGenerate": "Escrever com IA",
  "aiImprove": "Melhorar com IA",
  "aiBullets": "Sugerir marcadores",
  "aiSkills": "Sugerir competências com IA",
  "aiWorking": "A processar…",
  "aiError": "O pedido de IA falhou. Tente novamente.",
  "apply": "Aplicar",
  "copy": "Copiar",
  "copied": "Copiado",
  "aiOfflineNote": "Modo básico. Ligue um servidor de IA nas Definições para todas as funcionalidades.",
  "aiQuotaReached": "Limite diário gratuito de IA atingido",
  "aiFreeLeft": "Utilizações gratuitas de IA restantes hoje",
  "aiReview": "Analisar o meu currículo",
  "aiReviewHint": "Obtenha uma pontuação e dicas",
  "aiJobMatch": "Ajustar a uma vaga",
  "aiJobHint": "Cole uma vaga para ver as palavras-chave em falta",
  "aiJobField": "Descrição da vaga",
  "aiAnalyze": "Analisar",
  "aiCoverLetter": "Carta de apresentação",
  "aiCoverHint": "Escreva uma carta adaptada à vaga",
  "aiTranslate": "Traduzir currículo",
  "aiTranslateHint": "Crie uma cópia traduzida noutro idioma",
  "targetLanguage": "Idioma de destino",
  "aiTranslated": "Cópia traduzida criada",
  "aiTranslateNeedsServer": "A tradução requer um servidor de IA. Configure-o nas Definições.",
  "matchScore": "Correspondência",
  "matched": "Palavras-chave encontradas",
  "missingKw": "Palavras-chave em falta",
  "aiServer": "Endereço do servidor de IA",
  "aiServerHint": "Deixe vazio para usar o predefinido",
  "tips": "Dicas",
  "rvScore": "Pontuação do currículo",
  "rvSummaryShort": "O seu resumo é curto. Aponte para 2 a 4 frases.",
  "rvNoNumbers": "Acrescente números às suas conquistas (percentagens, valores, quantidades).",
  "rvFewSkills": "Indique pelo menos 6 competências relevantes.",
  "rvNoBullets": "Descreva a experiência com um marcador por conquista.",
  "rvGood": "O seu currículo parece sólido.",
  "clTemplate": "Exmos. Senhores,\n\nCandidato-me à vaga de {job}. Entre os meus pontos fortes estão {skills}, e teria todo o gosto em conversar sobre como posso contribuir para a vossa equipa.\n\nCom os melhores cumprimentos,\n{name}",
  "bulletHint": "acrescente o que fez e o resultado",
  "editPhoto": "Editar fotografia",
  "cropHint": "Arraste e faça zoom para recortar",
  "rotate": "Rodar",
  "filters": "Filtros",
  "brightness": "Brilho",
  "contrast": "Contraste",
  "saturation": "Saturação",
  "reset": "Repor",
  "f_original": "Original",
  "f_bw": "P&B",
  "f_sepia": "Sépia",
  "f_warm": "Quente",
  "f_cool": "Frio",
  "f_vivid": "Vívido",
  "f_fade": "Desbotado",
  "pickDate": "Escolher data",
  "clear": "Limpar",
  "share": "Partilhar",
  "saveFile": "Guardar",
  "saved": "Guardado",
  "saveFailed": "Não foi possível guardar o ficheiro",
  "sumYears": "{job} orientado para resultados com mais de {years} anos de experiência, focado em impacto mensurável e trabalho em equipa.",
  "sumPlain": "{job} motivado e com facilidade de aprendizagem, empenhado em gerar valor e crescer profissionalmente.",
  "sumSkills": "Pontos fortes: {skills}.",
  "fallbackJob": "profissional",
  "verbs": "Liderei|Desenvolvi|Lancei|Melhorei|Reduzi|Geri|Projetei|Alcancei|Entreguei|Aumentei",
  "softSkills": "Comunicação|Trabalho em equipa|Resolução de problemas|Gestão do tempo|Liderança|Adaptabilidade|Pensamento crítico|Criatividade|Atenção ao detalhe|Negociação|Atendimento ao cliente|Gestão de projetos|Capacidade analítica|Apresentações públicas",
};
