// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsPtBr = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Escolha o seu idioma",
  "myResumes": "Meus currículos",
  "newResume": "Novo currículo",
  "noResumes": "Ainda não há currículos",
  "noResumesHint": "Crie seu primeiro currículo profissional",
  "untitled": "Currículo sem título",
  "personal": "Dados pessoais",
  "summary": "Resumo",
  "experience": "Experiência",
  "education": "Formação",
  "skills": "Competências",
  "languages": "Idiomas",
  "projects": "Projetos",
  "design": "Design",
  "ai": "IA",
  "preview": "Pré-visualização e exportação",
  "settings": "Configurações",
  "uiLanguage": "Idioma do app",
  "premium": "Premium",
  "cancel": "Cancelar",
  "delete": "Excluir",
  "duplicate": "Duplicar",
  "confirmDelete": "Excluir este currículo?",
  "add": "Adicionar",
  "fullName": "Nome completo",
  "jobTitle": "Cargo",
  "email": "E-mail",
  "phone": "Celular",
  "city": "Cidade, País",
  "website": "Site ou LinkedIn",
  "company": "Empresa",
  "position": "Função",
  "location": "Local",
  "startDate": "Início",
  "endDate": "Fim",
  "present": "Atual",
  "description": "Descrição (um marcador por linha)",
  "school": "Instituição",
  "degree": "Grau / Área",
  "level": "Nível",
  "skillHint": "Adicionar competência",
  "projectName": "Nome do projeto",
  "projectLink": "Ligação",
  "langName": "Idioma",
  "suggestions": "Sugestões",
  "actionVerbs": "Verbos de ação para começar",
  "completeness": "Completude do currículo",
  "missing": "Em falta",
  "resumeLanguage": "Idioma do currículo",
  "accent": "Cor de destaque",
  "template": "Modelo",
  "photo": "Foto",
  "choosePhoto": "Escolher foto",
  "removePhoto": "Remover foto",
  "premiumTitle": "Modelo Premium",
  "premiumBody": "Este modelo faz parte do Premium.",
  "activateDemo": "Ativar (demo)",
  "premiumActive": "Premium ativo",
  "lv0": "Básico",
  "lv1": "Intermediário",
  "lv2": "Avançado",
  "lv3": "Fluente",
  "lv4": "Nativo",
  "tpl_classic": "Clássico",
  "tpl_modern": "Moderno",
  "tpl_minimal": "Minimalista",
  "tpl_banner": "Banner",
  "tpl_compact": "Compacto",
  "tpl_executive": "Executivo",
  "resumeName": "Nome do arquivo",
  "about": "Acerca de",
  "free": "Grátis",
  "aiTools": "Ferramentas de IA",
  "aiGenerate": "Escrever com IA",
  "aiImprove": "Melhorar com IA",
  "aiBullets": "Sugerir marcadores",
  "aiSkills": "Sugerir competências com IA",
  "aiWorking": "Processando…",
  "aiError": "A solicitação de IA falhou. Tente novamente.",
  "apply": "Aplicar",
  "copy": "Copiar",
  "copied": "Copiado",
  "aiOfflineNote": "Modo básico. Conecte um servidor de IA em Configurações para todos os recursos.",
  "aiQuotaReached": "Limite diário gratuito de IA atingido",
  "aiFreeLeft": "Utilizações gratuitas de IA restantes hoje",
  "aiReview": "Analisar meu currículo",
  "aiReviewHint": "Obtenha uma pontuação e dicas",
  "aiJobMatch": "Ajustar a uma vaga",
  "aiJobHint": "Cole uma vaga para ver as palavras-chave que faltam",
  "aiJobField": "Descrição da vaga",
  "aiAnalyze": "Analisar",
  "aiCoverLetter": "Carta de apresentação",
  "aiCoverHint": "Escreva uma carta adaptada à vaga",
  "aiTranslate": "Traduzir currículo",
  "aiTranslateHint": "Crie uma cópia traduzida em outro idioma",
  "targetLanguage": "Idioma de destino",
  "aiTranslated": "Cópia traduzida criada",
  "aiTranslateNeedsServer": "A tradução exige um servidor de IA. Configure-o em Configurações.",
  "matchScore": "Correspondência",
  "matched": "Palavras-chave encontradas",
  "missingKw": "Palavras-chave em falta",
  "aiServer": "Endereço do servidor de IA",
  "aiServerHint": "Deixe vazio para usar o predefinido",
  "tips": "Dicas",
  "rvScore": "Pontuação do currículo",
  "rvSummaryShort": "Seu resumo é curto. Mire em 2 a 4 frases.",
  "rvNoNumbers": "Adicione números às suas conquistas (porcentagens, valores, quantidades).",
  "rvFewSkills": "Liste pelo menos 6 competências relevantes.",
  "rvNoBullets": "Descreva sua experiência com um marcador por conquista.",
  "rvGood": "Seu currículo parece sólido.",
  "clTemplate": "Prezados,\n\nCandidato-me à vaga de {job}. Entre meus pontos fortes estão {skills}, e gostaria de conversar sobre como posso contribuir com a equipe de vocês.\n\nAtenciosamente,\n{name}",
  "bulletHint": "acrescente o que fez e o resultado",
  "editPhoto": "Editar foto",
  "cropHint": "Arraste e faça zoom para cortar",
  "rotate": "Girar",
  "filters": "Filtros",
  "brightness": "Brilho",
  "contrast": "Contraste",
  "saturation": "Saturação",
  "reset": "Redefinir",
  "f_original": "Original",
  "f_bw": "P&B",
  "f_sepia": "Sépia",
  "f_warm": "Quente",
  "f_cool": "Frio",
  "f_vivid": "Vívido",
  "f_fade": "Desbotado",
  "pickDate": "Escolher data",
  "clear": "Limpar",
  "share": "Compartilhar",
  "saveFile": "Salvar",
  "saved": "Salvo",
  "saveFailed": "Não foi possível salvar o arquivo",
  "sumYears": "{job} orientado a resultados com mais de {years} anos de experiência, focado em impacto mensurável e trabalho em equipe.",
  "sumPlain": "{job} motivado e com facilidade para aprender, disposto a gerar valor e crescer profissionalmente.",
  "sumSkills": "Pontos fortes: {skills}.",
  "fallbackJob": "profissional",
  "verbs": "Liderei|Desenvolvi|Lancei|Melhorei|Reduzi|Gerenciei|Projetei|Alcancei|Entreguei|Aumentei",
  "softSkills": "Comunicação|Trabalho em equipe|Resolução de problemas|Gestão do tempo|Liderança|Adaptabilidade|Pensamento crítico|Criatividade|Atenção aos detalhes|Negociação|Atendimento ao cliente|Gerenciamento de projetos|Capacidade analítica|Apresentações em público",
};
