// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsRo = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Alege limba",
  "myResumes": "CV-urile mele",
  "newResume": "CV nou",
  "noResumes": "Niciun CV încă",
  "noResumesHint": "Creează primul tău CV profesional",
  "untitled": "CV fără titlu",
  "personal": "Date personale",
  "summary": "Rezumat",
  "experience": "Experiență",
  "education": "Educație",
  "skills": "Competențe",
  "languages": "Limbi",
  "projects": "Proiecte",
  "design": "Design",
  "ai": "IA",
  "preview": "Previzualizare și export",
  "settings": "Setări",
  "uiLanguage": "Limba aplicației",
  "premium": "Premium",
  "cancel": "Anulează",
  "delete": "Șterge",
  "duplicate": "Duplică",
  "confirmDelete": "Ștergi acest CV?",
  "add": "Adaugă",
  "fullName": "Nume complet",
  "jobTitle": "Funcție",
  "email": "E-mail",
  "phone": "Telefon",
  "city": "Oraș, țară",
  "website": "Site web sau LinkedIn",
  "company": "Companie",
  "position": "Poziție",
  "location": "Locație",
  "startDate": "Început",
  "endDate": "Sfârșit",
  "present": "Prezent",
  "description": "Descriere (o linie per punct)",
  "school": "Instituție",
  "degree": "Diplomă / Domeniu",
  "level": "Nivel",
  "skillHint": "Adaugă o competență",
  "projectName": "Numele proiectului",
  "projectLink": "Link",
  "langName": "Limbă",
  "suggestions": "Sugestii",
  "actionVerbs": "Verbe de acțiune cu care să începi",
  "completeness": "Completitudinea CV-ului",
  "missing": "Lipsește",
  "resumeLanguage": "Limba CV-ului",
  "accent": "Culoare principală",
  "template": "Șablon",
  "photo": "Fotografie",
  "choosePhoto": "Alege fotografia",
  "removePhoto": "Elimină fotografia",
  "premiumTitle": "Șablon Premium",
  "premiumBody": "Acest șablon face parte din Premium.",
  "activateDemo": "Activează (demo)",
  "premiumActive": "Premium este activ",
  "lv0": "Elementar",
  "lv1": "Intermediar",
  "lv2": "Avansat",
  "lv3": "Fluent",
  "lv4": "Nativ",
  "tpl_classic": "Clasic",
  "tpl_modern": "Modern",
  "tpl_minimal": "Minimalist",
  "tpl_banner": "Banner",
  "tpl_compact": "Compact",
  "tpl_executive": "Executiv",
  "resumeName": "Numele fișierului",
  "about": "Despre",
  "free": "Gratuit",
  "aiTools": "Instrumente IA",
  "aiGenerate": "Scrie cu IA",
  "aiImprove": "Îmbunătățește cu IA",
  "aiBullets": "Sugerează puncte",
  "aiSkills": "Sugerează competențe cu IA",
  "aiWorking": "Se lucrează…",
  "aiError": "Cererea IA a eșuat. Încearcă din nou.",
  "apply": "Aplică",
  "copy": "Copiază",
  "copied": "Copiat",
  "aiOfflineNote": "Mod de bază. Conectează un server IA în Setări pentru toate funcțiile.",
  "aiQuotaReached": "Limita zilnică gratuită de IA a fost atinsă",
  "aiFreeLeft": "Utilizări IA gratuite rămase astăzi",
  "aiReview": "Analizează CV-ul meu",
  "aiReviewHint": "Primești un scor și sfaturi",
  "aiJobMatch": "Potrivește cu un job",
  "aiJobHint": "Lipește anunțul pentru a vedea cuvintele-cheie lipsă",
  "aiJobField": "Descrierea jobului",
  "aiAnalyze": "Analizează",
  "aiCoverLetter": "Scrisoare de intenție",
  "aiCoverHint": "Scrie o scrisoare adaptată jobului",
  "aiTranslate": "Tradu CV-ul",
  "aiTranslateHint": "Creează o copie tradusă în altă limbă",
  "targetLanguage": "Limba țintă",
  "aiTranslated": "Copia tradusă a fost creată",
  "aiTranslateNeedsServer": "Traducerea necesită un server IA. Configurează-l în Setări.",
  "matchScore": "Potrivire",
  "matched": "Cuvinte-cheie găsite",
  "missingKw": "Cuvinte-cheie lipsă",
  "aiServer": "Adresa serverului IA",
  "aiServerHint": "Lasă gol pentru valoarea implicită",
  "tips": "Sfaturi",
  "rvScore": "Scorul CV-ului",
  "rvSummaryShort": "Rezumatul este scurt. Țintește 2-4 propoziții.",
  "rvNoNumbers": "Adaugă cifre realizărilor tale (procente, sume, cantități).",
  "rvFewSkills": "Enumeră cel puțin 6 competențe relevante.",
  "rvNoBullets": "Descrie experiența cu un punct pentru fiecare realizare.",
  "rvGood": "CV-ul tău arată bine.",
  "clTemplate": "Stimată doamnă / Stimate domn,\n\nVă scriu pentru a mă candida la postul de {job}. Printre punctele mele forte se numără {skills}, iar mi-ar face plăcere să discutăm cum pot contribui la echipa dumneavoastră.\n\nCu stimă,\n{name}",
  "bulletHint": "adaugă ce ai făcut și rezultatul",
  "editPhoto": "Editează fotografia",
  "cropHint": "Trage și ciupește pentru a decupa",
  "rotate": "Rotește",
  "filters": "Filtre",
  "brightness": "Luminozitate",
  "contrast": "Contrast",
  "saturation": "Saturație",
  "reset": "Resetează",
  "f_original": "Original",
  "f_bw": "Alb-negru",
  "f_sepia": "Sepia",
  "f_warm": "Cald",
  "f_cool": "Rece",
  "f_vivid": "Intens",
  "f_fade": "Șters",
  "pickDate": "Alege data",
  "clear": "Șterge",
  "share": "Distribuie",
  "saveFile": "Salvează",
  "saved": "Salvat",
  "saveFailed": "Fișierul nu a putut fi salvat",
  "sumYears": "{job} orientat spre rezultate, cu peste {years} ani de experiență, concentrat pe impact măsurabil și colaborare în echipă.",
  "sumPlain": "{job} motivat, care învață rapid, dornic să aducă valoare reală și să evolueze profesional.",
  "sumSkills": "Puncte forte: {skills}.",
  "fallbackJob": "profesionist",
  "verbs": "Am condus|Am dezvoltat|Am lansat|Am îmbunătățit|Am redus|Am gestionat|Am proiectat|Am realizat|Am livrat|Am crescut",
  "softSkills": "Comunicare|Lucru în echipă|Rezolvarea problemelor|Managementul timpului|Leadership|Adaptabilitate|Gândire critică|Creativitate|Atenție la detalii|Negociere|Servicii clienți|Managementul proiectelor|Gândire analitică|Prezentări publice",
};
