// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsTr = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Dilinizi seçin",
  "myResumes": "Özgeçmişlerim",
  "newResume": "Yeni özgeçmiş",
  "noResumes": "Henüz özgeçmiş yok",
  "noResumesHint": "İlk profesyonel özgeçmişinizi oluşturun",
  "untitled": "Başlıksız özgeçmiş",
  "personal": "Kişisel bilgiler",
  "summary": "Özet",
  "experience": "Deneyim",
  "education": "Eğitim",
  "skills": "Beceriler",
  "languages": "Diller",
  "projects": "Projeler",
  "design": "Tasarım",
  "ai": "Yapay zekâ",
  "preview": "Önizleme ve dışa aktar",
  "settings": "Ayarlar",
  "uiLanguage": "Uygulama dili",
  "premium": "Premium",
  "cancel": "İptal",
  "delete": "Sil",
  "duplicate": "Kopyala",
  "confirmDelete": "Bu özgeçmiş silinsin mi?",
  "add": "Ekle",
  "fullName": "Ad soyad",
  "jobTitle": "Unvan",
  "email": "E-posta",
  "phone": "Telefon",
  "city": "Şehir, Ülke",
  "website": "Web sitesi veya LinkedIn",
  "company": "Şirket",
  "position": "Pozisyon",
  "location": "Konum",
  "startDate": "Başlangıç",
  "endDate": "Bitiş",
  "present": "Devam ediyor",
  "description": "Açıklama (her satır bir madde)",
  "school": "Okul",
  "degree": "Derece / Bölüm",
  "level": "Seviye",
  "skillHint": "Beceri ekle",
  "projectName": "Proje adı",
  "projectLink": "Bağlantı",
  "langName": "Dil",
  "suggestions": "Öneriler",
  "actionVerbs": "Başlamak için güçlü fiiller",
  "completeness": "Özgeçmiş doluluğu",
  "missing": "Eksik",
  "resumeLanguage": "Özgeçmiş dili",
  "accent": "Ana renk",
  "template": "Şablon",
  "photo": "Fotoğraf",
  "choosePhoto": "Fotoğraf seç",
  "removePhoto": "Fotoğrafı kaldır",
  "premiumTitle": "Premium şablon",
  "premiumBody": "Bu şablon Premium kapsamındadır.",
  "activateDemo": "Etkinleştir (demo)",
  "premiumActive": "Premium etkin",
  "lv0": "Temel",
  "lv1": "Orta",
  "lv2": "İleri",
  "lv3": "Akıcı",
  "lv4": "Ana dil",
  "tpl_classic": "Klasik",
  "tpl_modern": "Modern",
  "tpl_minimal": "Minimal",
  "tpl_banner": "Başlık",
  "tpl_compact": "Kompakt",
  "tpl_executive": "Yönetici",
  "resumeName": "Dosya adı",
  "about": "Hakkında",
  "free": "Ücretsiz",
  "aiTools": "Yapay zekâ araçları",
  "aiGenerate": "Yapay zekâ ile yaz",
  "aiImprove": "Yapay zekâ ile geliştir",
  "aiBullets": "Madde önerileri al",
  "aiSkills": "Yapay zekâ ile beceri öner",
  "aiWorking": "Çalışıyor…",
  "aiError": "Yapay zekâ isteği başarısız. Tekrar deneyin.",
  "apply": "Uygula",
  "copy": "Kopyala",
  "copied": "Kopyalandı",
  "aiOfflineNote": "Temel mod. Tüm özellikler için Ayarlar'dan bir yapay zekâ sunucusu bağlayın.",
  "aiQuotaReached": "Günlük ücretsiz yapay zekâ sınırına ulaşıldı",
  "aiFreeLeft": "Bugün kalan ücretsiz yapay zekâ hakkı",
  "aiReview": "Özgeçmişimi incele",
  "aiReviewHint": "Puan ve iyileştirme önerileri alın",
  "aiJobMatch": "İlanla eşleştir",
  "aiJobHint": "Eksik anahtar kelimeleri görmek için iş ilanını yapıştırın",
  "aiJobField": "İş tanımı",
  "aiAnalyze": "Analiz et",
  "aiCoverLetter": "Ön yazı",
  "aiCoverHint": "İlana özel bir ön yazı hazırlayın",
  "aiTranslate": "Özgeçmişi çevir",
  "aiTranslateHint": "Başka bir dilde çevrilmiş kopya oluşturun",
  "targetLanguage": "Hedef dil",
  "aiTranslated": "Çevrilmiş kopya oluşturuldu",
  "aiTranslateNeedsServer": "Çeviri için yapay zekâ sunucusu gerekir. Ayarlar'dan yapılandırın.",
  "matchScore": "Eşleşme",
  "matched": "Eşleşen anahtar kelimeler",
  "missingKw": "Eksik anahtar kelimeler",
  "aiServer": "Yapay zekâ sunucu adresi",
  "aiServerHint": "Varsayılanı kullanmak için boş bırakın",
  "tips": "İpuçları",
  "rvScore": "Özgeçmiş puanı",
  "rvSummaryShort": "Özetiniz kısa. 2 ila 4 cümle hedefleyin.",
  "rvNoNumbers": "Başarılarınıza rakam ekleyin (yüzde, tutar, adet).",
  "rvFewSkills": "En az 6 ilgili beceri ekleyin.",
  "rvNoBullets": "Deneyiminizi her başarı için bir madde ile anlatın.",
  "rvGood": "Özgeçmişiniz güçlü görünüyor.",
  "clTemplate": "Sayın İşe Alım Yetkilisi,\n\n{job} pozisyonuna başvurmak için yazıyorum. Güçlü yönlerim arasında {skills} bulunmaktadır ve ekibinize nasıl katkı sağlayabileceğimi görüşme fırsatından memnuniyet duyarım.\n\nSaygılarımla,\n{name}",
  "bulletHint": "ne yaptığınızı ve sonucu ekleyin",
  "editPhoto": "Fotoğrafı düzenle",
  "cropHint": "Kırpmak için sürükleyin ve sıkıştırın",
  "rotate": "Döndür",
  "filters": "Filtreler",
  "brightness": "Parlaklık",
  "contrast": "Kontrast",
  "saturation": "Doygunluk",
  "reset": "Sıfırla",
  "f_original": "Orijinal",
  "f_bw": "Siyah beyaz",
  "f_sepia": "Sepya",
  "f_warm": "Sıcak",
  "f_cool": "Soğuk",
  "f_vivid": "Canlı",
  "f_fade": "Soluk",
  "pickDate": "Tarih seç",
  "clear": "Temizle",
  "share": "Paylaş",
  "saveFile": "Kaydet",
  "saved": "Kaydedildi",
  "saveFailed": "Dosya kaydedilemedi",
  "sumYears": "{years}+ yıllık deneyime sahip, sonuç odaklı {job}; ölçülebilir etki yaratmaya ve ekip çalışmasına odaklıdır.",
  "sumPlain": "Motive ve hızlı öğrenen {job}; gerçek değer katmak ve kendini geliştirmek istiyor.",
  "sumSkills": "Güçlü yönler: {skills}.",
  "fallbackJob": "profesyonel",
  "verbs": "Yönettim|Geliştirdim|Başlattım|İyileştirdim|Azalttım|Tasarladım|Sağladım|Ulaştım|Teslim ettim|Artırdım",
  "softSkills": "İletişim|Takım çalışması|Problem çözme|Zaman yönetimi|Liderlik|Uyum sağlama|Eleştirel düşünme|Yaratıcılık|Detaylara dikkat|Müzakere|Müşteri hizmetleri|Proje yönetimi|Analitik düşünme|Topluluk önünde konuşma",
};
