// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsVi = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "Chọn ngôn ngữ của bạn",
  "myResumes": "CV của tôi",
  "newResume": "CV mới",
  "noResumes": "Chưa có CV nào",
  "noResumesHint": "Tạo CV chuyên nghiệp đầu tiên của bạn",
  "untitled": "CV chưa đặt tên",
  "personal": "Thông tin cá nhân",
  "summary": "Giới thiệu",
  "experience": "Kinh nghiệm",
  "education": "Học vấn",
  "skills": "Kỹ năng",
  "languages": "Ngôn ngữ",
  "projects": "Dự án",
  "design": "Thiết kế",
  "ai": "AI",
  "preview": "Xem trước & xuất",
  "settings": "Cài đặt",
  "uiLanguage": "Ngôn ngữ ứng dụng",
  "premium": "Premium",
  "cancel": "Hủy",
  "delete": "Xóa",
  "duplicate": "Nhân bản",
  "confirmDelete": "Xóa CV này?",
  "add": "Thêm",
  "fullName": "Họ và tên",
  "jobTitle": "Chức danh",
  "email": "Email",
  "phone": "Điện thoại",
  "city": "Thành phố, Quốc gia",
  "website": "Website hoặc LinkedIn",
  "company": "Công ty",
  "position": "Vị trí",
  "location": "Địa điểm",
  "startDate": "Bắt đầu",
  "endDate": "Kết thúc",
  "present": "Hiện tại",
  "description": "Mô tả (mỗi dòng một ý)",
  "school": "Trường",
  "degree": "Bằng cấp / Ngành",
  "level": "Trình độ",
  "skillHint": "Thêm kỹ năng",
  "projectName": "Tên dự án",
  "projectLink": "Liên kết",
  "langName": "Ngôn ngữ",
  "suggestions": "Gợi ý",
  "actionVerbs": "Động từ mạnh để bắt đầu",
  "completeness": "Mức hoàn thiện của CV",
  "missing": "Còn thiếu",
  "resumeLanguage": "Ngôn ngữ CV",
  "accent": "Màu chủ đạo",
  "template": "Mẫu",
  "photo": "Ảnh",
  "choosePhoto": "Chọn ảnh",
  "removePhoto": "Xóa ảnh",
  "premiumTitle": "Mẫu Premium",
  "premiumBody": "Mẫu này thuộc gói Premium.",
  "activateDemo": "Kích hoạt (demo)",
  "premiumActive": "Premium đang hoạt động",
  "lv0": "Cơ bản",
  "lv1": "Trung cấp",
  "lv2": "Nâng cao",
  "lv3": "Thành thạo",
  "lv4": "Bản ngữ",
  "tpl_classic": "Cổ điển",
  "tpl_modern": "Hiện đại",
  "tpl_minimal": "Tối giản",
  "tpl_banner": "Biểu ngữ",
  "tpl_compact": "Gọn",
  "tpl_executive": "Điều hành",
  "resumeName": "Tên tệp",
  "about": "Giới thiệu ứng dụng",
  "free": "Miễn phí",
  "aiTools": "Công cụ AI",
  "aiGenerate": "Viết bằng AI",
  "aiImprove": "Cải thiện bằng AI",
  "aiBullets": "Gợi ý các ý chính",
  "aiSkills": "Gợi ý kỹ năng bằng AI",
  "aiWorking": "Đang xử lý…",
  "aiError": "Yêu cầu AI thất bại. Vui lòng thử lại.",
  "apply": "Áp dụng",
  "copy": "Sao chép",
  "copied": "Đã sao chép",
  "aiOfflineNote": "Chế độ cơ bản. Kết nối máy chủ AI trong Cài đặt để dùng đầy đủ.",
  "aiQuotaReached": "Đã hết lượt AI miễn phí trong ngày",
  "aiFreeLeft": "Lượt AI miễn phí còn lại hôm nay",
  "aiReview": "Đánh giá CV của tôi",
  "aiReviewHint": "Nhận điểm số và mẹo cải thiện",
  "aiJobMatch": "Đối chiếu với tin tuyển dụng",
  "aiJobHint": "Dán mô tả công việc để xem các từ khóa còn thiếu",
  "aiJobField": "Mô tả công việc",
  "aiAnalyze": "Phân tích",
  "aiCoverLetter": "Thư xin việc",
  "aiCoverHint": "Viết thư xin việc phù hợp với vị trí",
  "aiTranslate": "Dịch CV",
  "aiTranslateHint": "Tạo bản sao đã dịch sang ngôn ngữ khác",
  "targetLanguage": "Ngôn ngữ đích",
  "aiTranslated": "Đã tạo bản sao đã dịch",
  "aiTranslateNeedsServer": "Dịch cần máy chủ AI. Hãy thiết lập trong Cài đặt.",
  "matchScore": "Độ phù hợp",
  "matched": "Từ khóa khớp",
  "missingKw": "Từ khóa còn thiếu",
  "aiServer": "Địa chỉ máy chủ AI",
  "aiServerHint": "Để trống để dùng mặc định",
  "tips": "Mẹo",
  "rvScore": "Điểm CV",
  "rvSummaryShort": "Phần giới thiệu hơi ngắn. Nên viết 2 đến 4 câu.",
  "rvNoNumbers": "Thêm số liệu vào thành tích (phần trăm, số tiền, số lượng).",
  "rvFewSkills": "Liệt kê ít nhất 6 kỹ năng phù hợp.",
  "rvNoBullets": "Mô tả kinh nghiệm với mỗi thành tích một ý.",
  "rvGood": "CV của bạn trông rất tốt.",
  "clTemplate": "Kính gửi Quý công ty,\n\nTôi viết thư này để ứng tuyển vị trí {job}. Điểm mạnh của tôi gồm {skills}, và tôi mong có cơ hội trao đổi về những đóng góp cho đội ngũ của Quý công ty.\n\nTrân trọng,\n{name}",
  "bulletHint": "thêm việc bạn đã làm và kết quả",
  "editPhoto": "Chỉnh sửa ảnh",
  "cropHint": "Kéo và chụm để cắt",
  "rotate": "Xoay",
  "filters": "Bộ lọc",
  "brightness": "Độ sáng",
  "contrast": "Độ tương phản",
  "saturation": "Độ bão hòa",
  "reset": "Đặt lại",
  "f_original": "Gốc",
  "f_bw": "Đen trắng",
  "f_sepia": "Sepia",
  "f_warm": "Ấm",
  "f_cool": "Lạnh",
  "f_vivid": "Rực rỡ",
  "f_fade": "Nhạt",
  "pickDate": "Chọn ngày",
  "clear": "Xóa",
  "share": "Chia sẻ",
  "saveFile": "Lưu",
  "saved": "Đã lưu",
  "saveFailed": "Không thể lưu tệp",
  "sumYears": "{job} định hướng kết quả với hơn {years} năm kinh nghiệm, tập trung tạo tác động đo lường được và làm việc nhóm hiệu quả.",
  "sumPlain": "{job} có động lực, học hỏi nhanh, mong muốn tạo giá trị thực và không ngừng phát triển.",
  "sumSkills": "Điểm mạnh: {skills}.",
  "fallbackJob": "chuyên gia",
  "verbs": "Dẫn dắt|Xây dựng|Triển khai|Cải thiện|Giảm|Quản lý|Thiết kế|Đạt được|Bàn giao|Tăng",
  "softSkills": "Giao tiếp|Làm việc nhóm|Giải quyết vấn đề|Quản lý thời gian|Lãnh đạo|Khả năng thích ứng|Tư duy phản biện|Sáng tạo|Chú ý chi tiết|Đàm phán|Chăm sóc khách hàng|Quản lý dự án|Tư duy phân tích|Thuyết trình",
};
