// GENERATED FILE. Edit the translation sources, not this file.
const Map<String, String> stringsZh = {
  "appName": "Free AI CV Maker",
  "chooseLanguage": "选择您的语言",
  "myResumes": "我的简历",
  "newResume": "新建简历",
  "noResumes": "还没有简历",
  "noResumesHint": "创建您的第一份专业简历",
  "untitled": "未命名简历",
  "personal": "个人信息",
  "summary": "个人简介",
  "experience": "工作经历",
  "education": "教育背景",
  "skills": "技能",
  "languages": "语言",
  "projects": "项目经历",
  "design": "设计",
  "ai": "AI",
  "preview": "预览与导出",
  "settings": "设置",
  "uiLanguage": "应用语言",
  "premium": "高级版",
  "cancel": "取消",
  "delete": "删除",
  "duplicate": "复制",
  "confirmDelete": "确定删除这份简历吗？",
  "add": "添加",
  "fullName": "姓名",
  "jobTitle": "职位",
  "email": "邮箱",
  "phone": "电话",
  "city": "城市、国家",
  "website": "网站或 LinkedIn",
  "company": "公司",
  "position": "职务",
  "location": "地点",
  "startDate": "开始",
  "endDate": "结束",
  "present": "至今",
  "description": "描述（每行一条）",
  "school": "院校",
  "degree": "学位 / 专业",
  "level": "水平",
  "skillHint": "添加技能",
  "projectName": "项目名称",
  "projectLink": "链接",
  "langName": "语言",
  "suggestions": "建议",
  "actionVerbs": "适合开头的有力动词",
  "completeness": "简历完整度",
  "missing": "缺少",
  "resumeLanguage": "简历语言",
  "accent": "主题色",
  "template": "模板",
  "photo": "照片",
  "choosePhoto": "选择照片",
  "removePhoto": "移除照片",
  "premiumTitle": "高级模板",
  "premiumBody": "此模板属于高级版。",
  "activateDemo": "激活（演示）",
  "premiumActive": "高级版已启用",
  "lv0": "入门",
  "lv1": "中级",
  "lv2": "高级",
  "lv3": "流利",
  "lv4": "母语",
  "tpl_classic": "经典",
  "tpl_modern": "现代",
  "tpl_minimal": "极简",
  "tpl_banner": "横幅",
  "tpl_compact": "紧凑",
  "tpl_executive": "商务",
  "resumeName": "文件名",
  "about": "关于",
  "free": "免费",
  "aiTools": "AI 工具",
  "aiGenerate": "用 AI 撰写",
  "aiImprove": "用 AI 优化",
  "aiBullets": "推荐要点",
  "aiSkills": "用 AI 推荐技能",
  "aiWorking": "处理中…",
  "aiError": "AI 请求失败，请重试。",
  "apply": "应用",
  "copy": "复制",
  "copied": "已复制",
  "aiOfflineNote": "基础模式。请在设置中连接 AI 服务器以使用完整功能。",
  "aiQuotaReached": "今日免费 AI 次数已用完",
  "aiFreeLeft": "今日剩余免费 AI 次数",
  "aiReview": "评估我的简历",
  "aiReviewHint": "获取评分和改进建议",
  "aiJobMatch": "匹配职位",
  "aiJobHint": "粘贴职位描述，查看缺少的关键词",
  "aiJobField": "职位描述",
  "aiAnalyze": "分析",
  "aiCoverLetter": "求职信",
  "aiCoverHint": "撰写针对该职位的求职信",
  "aiTranslate": "翻译简历",
  "aiTranslateHint": "创建另一种语言的翻译副本",
  "targetLanguage": "目标语言",
  "aiTranslated": "已创建翻译副本",
  "aiTranslateNeedsServer": "翻译需要 AI 服务器，请在设置中配置。",
  "matchScore": "匹配度",
  "matched": "已匹配关键词",
  "missingKw": "缺少的关键词",
  "aiServer": "AI 服务器地址",
  "aiServerHint": "留空则使用默认值",
  "tips": "提示",
  "rvScore": "简历评分",
  "rvSummaryShort": "个人简介偏短，建议写 2 到 4 句。",
  "rvNoNumbers": "请为成果添加数据（百分比、金额、数量）。",
  "rvFewSkills": "请至少列出 6 项相关技能。",
  "rvNoBullets": "请用要点描述经历，每项成果一条。",
  "rvGood": "您的简历看起来很出色。",
  "clTemplate": "尊敬的招聘负责人：\n\n我谨此申请{job}一职。我的优势包括{skills}，期待有机会与您交流我能为团队带来的价值。\n\n此致\n敬礼\n{name}",
  "bulletHint": "补充您做了什么以及结果",
  "editPhoto": "编辑照片",
  "cropHint": "拖动并双指缩放以裁剪",
  "rotate": "旋转",
  "filters": "滤镜",
  "brightness": "亮度",
  "contrast": "对比度",
  "saturation": "饱和度",
  "reset": "重置",
  "f_original": "原图",
  "f_bw": "黑白",
  "f_sepia": "怀旧",
  "f_warm": "暖色",
  "f_cool": "冷色",
  "f_vivid": "鲜艳",
  "f_fade": "褪色",
  "pickDate": "选择日期",
  "clear": "清除",
  "share": "分享",
  "saveFile": "保存",
  "saved": "已保存",
  "saveFailed": "无法保存文件",
  "sumYears": "拥有{years}年以上经验的结果导向型{job}，专注于创造可衡量的成果并善于团队协作。",
  "sumPlain": "积极主动、学习能力强的{job}，渴望创造真实价值并持续成长。",
  "sumSkills": "优势包括：{skills}。",
  "fallbackJob": "专业人士",
  "verbs": "带领|搭建|上线|优化|降低|管理|设计|达成|交付|提升",
  "softSkills": "沟通能力|团队协作|解决问题|时间管理|领导力|适应能力|批判性思维|创造力|注重细节|谈判能力|客户服务|项目管理|分析能力|公开演讲",
};
